import type { Question } from "./content";
// Original short clues. IDs are stable; existing q1–q30 remain untouched.
const rows = [
  [
    "DAVA",
    "Bir hakkın korunması için mahkemeden hukuki yardım istenmesi.",
    "Usul",
  ],
  ["DAVACI", "Mahkemede talepte bulunarak davayı açan taraf.", "Usul"],
  ["DAVALI", "Davada kendisine karşı talepte bulunulan taraf.", "Usul"],
  [
    "HÜKÜM",
    "Mahkemenin uyuşmazlığın esası hakkında verdiği son karar.",
    "Usul",
  ],
  ["İLAM", "Mahkeme hükmünün taraflara verilen resmî yazılı örneği.", "Usul"],
  [
    "DURUŞMA",
    "Yargılamada tarafların ve delillerin mahkeme önünde ele alındığı oturum.",
    "Usul",
  ],
  ["DİLEKÇE", "Bir makama istek veya şikâyet bildiren yazılı başvuru.", "Usul"],
  [
    "YETKİ",
    "Bir davaya hangi yer mahkemesinin bakacağını belirleyen alan.",
    "Usul",
  ],
  [
    "GÖREV",
    "Bir davaya hangi tür mahkemenin bakacağını belirleyen alan.",
    "Usul",
  ],
  [
    "İSPAT",
    "Bir vakıanın doğruluğu konusunda mahkemede kanaat oluşturma faaliyeti.",
    "Usul",
  ],
  [
    "KARİNE",
    "Bilinen bir olgudan bilinmeyen bir olgu hakkında çıkarılan sonuç.",
    "Usul",
  ],
  [
    "YEMİN",
    "Kanunun öngördüğü biçimde gerçeği söylediğini doğrulayan beyan.",
    "Usul",
  ],
  [
    "KEŞİF",
    "Mahkemenin bir yer veya nesne hakkında doğrudan gözlem yapması.",
    "Usul",
  ],
  [
    "ISLAH",
    "Tarafın yaptığı usul işlemlerini kanuni koşullarla düzeltmesi.",
    "Usul",
  ],
  [
    "SULH",
    "Tarafların aralarındaki uyuşmazlığı anlaşarak sona erdirmesi.",
    "Usul",
  ],
  [
    "TAHKİM",
    "Uyuşmazlığın devlet mahkemesi yerine hakemlerce çözülmesi yöntemi.",
    "Usul",
  ],
  ["HAKEM", "Tahkimde uyuşmazlığı çözmek üzere görevlendirilen kişi.", "Usul"],
  [
    "TENSİP",
    "Dava açılınca yargılamanın yürütülmesine ilişkin ilk hazırlık kararları.",
    "Usul",
  ],
  [
    "İTİRAZ",
    "Bir işleme veya karara karşı çıkıldığını bildiren hukuki başvuru.",
    "Usul",
  ],
  [
    "MÜLKİYET",
    "Bir şey üzerinde kullanma, yararlanma ve tasarruf yetkileri veren hak.",
    "Eşya",
  ],
  ["PAYDAŞ", "Paylı mülkiyette belirli bir payın sahibi olan kişi.", "Eşya"],
  [
    "İRTİFAK",
    "Bir eşya üzerinde başkası yararına sınırlı yararlanma sağlayan ayni hak.",
    "Eşya",
  ],
  [
    "REHİN",
    "Bir alacağı güvence altına almak için eşya veya hak üzerinde kurulan teminat.",
    "Eşya",
  ],
  ["TAPU", "Taşınmazlar üzerindeki hakların kaydedildiği resmî sicil.", "Eşya"],
  [
    "TESCİL",
    "Bir hakkın veya hukuki durumun ilgili resmî sicile kaydedilmesi.",
    "Eşya",
  ],
  ["TERKİN", "Bir kaydın ilgili sicilden silinmesi işlemi.", "Eşya"],
  [
    "ŞERH",
    "Bir hususun tapu siciline açıklayıcı veya koruyucu kayıt olarak yazılması.",
    "Eşya",
  ],
  [
    "KADASTRO",
    "Taşınmazların sınır ve hukuki durumlarının belirlenip kayıt altına alınması.",
    "Eşya",
  ],
  ["TAŞINMAZ", "Arazi gibi yerinden taşınamayan mal türü.", "Eşya"],
  ["TAŞINIR", "Bir yerden başka yere taşınabilen eşya türü.", "Eşya"],
  [
    "İYİNİYET",
    "Hukuki bir engeli gerekli özeni gösterdiği hâlde bilmemeyi anlatan kavram.",
    "Medeni",
  ],
  [
    "EHLİYET",
    "Hak sahibi olabilme veya hukuki işlem yapabilme yeterliliği.",
    "Medeni",
  ],
  [
    "ERGİNLİK",
    "Kişinin hukukça yetişkin sayılmasını ifade eden durum.",
    "Medeni",
  ],
  [
    "GAİPLİK",
    "Ölüm tehlikesi içinde kaybolan veya uzun süre haber alınamayan kişi hakkında verilen karar.",
    "Medeni",
  ],
  [
    "HISIMLIK",
    "Kişiler arasında soy, evlilik veya evlat edinmeyle oluşan yakınlık bağı.",
    "Medeni",
  ],
  ["SOYBAĞI", "Çocuk ile ana veya babası arasındaki hukuki bağ.", "Aile"],
  ["NİŞANLANMA", "Birbirleriyle evlenmek üzere karşılıklı söz verme.", "Aile"],
  ["BOŞANMA", "Geçerli evliliğin mahkeme kararıyla sona ermesi.", "Aile"],
  ["TEREKE", "Ölen kişinin mirasa konu hak ve borçlarının bütünü.", "Miras"],
  [
    "MİRASÇI",
    "Ölenin mirasında kanun veya ölüme bağlı tasarrufla hak sahibi olan kişi.",
    "Miras",
  ],
  [
    "TENKİS",
    "Saklı payı aşan ölüme bağlı kazandırmaların kanuni sınıra indirilmesi.",
    "Miras",
  ],
  [
    "EDİM",
    "Borç ilişkisinde borçlunun yerine getirmesi gereken davranış.",
    "Borçlar",
  ],
  ["İFA", "Borçlanılan edimin gereği gibi yerine getirilmesi.", "Borçlar"],
  [
    "ALACAK",
    "Borç ilişkisinde karşı taraftan bir edimi isteme hakkı.",
    "Borçlar",
  ],
  [
    "BORÇLU",
    "Bir borç ilişkisinde edimi yerine getirmekle yükümlü kişi.",
    "Borçlar",
  ],
  [
    "ALACAKLI",
    "Borçludan edimin yerine getirilmesini istemeye yetkili kişi.",
    "Borçlar",
  ],
  [
    "SÖZLEŞME",
    "Tarafların birbirine uygun irade açıklamalarıyla kurulan hukuki işlem.",
    "Borçlar",
  ],
  [
    "İCAP",
    "Bir sözleşmeyi kurmaya yönelik bağlayıcı önerinin geleneksel adı.",
    "Borçlar",
  ],
  ["KABUL", "Sözleşme önerisine uygun olumlu irade açıklaması.", "Borçlar"],
  [
    "GABİN",
    "Sözleşmede zor durumdan veya deneyimsizlikten yararlanılarak sağlanan aşırı yararlanmanın eski adı.",
    "Borçlar",
  ],
  [
    "HİLE",
    "Bir kişiyi hukuki işlem yapmaya yöneltmek için aldatma.",
    "Borçlar",
  ],
  [
    "İKRAH",
    "Kişiyi korkutarak hukuki işlem yapmaya yöneltmenin geleneksel adı.",
    "Borçlar",
  ],
  [
    "MUVAZAA",
    "Tarafların gerçek iradelerine uymayan görünüşte bir işlem yapmaları.",
    "Borçlar",
  ],
  [
    "BUTLAN",
    "Bir hukuki işlemin geçerlilik şartlarındaki eksiklik nedeniyle hükümsüz olması.",
    "Borçlar",
  ],
  [
    "FESİH",
    "Süregelen bir sözleşme ilişkisini ileriye etkili sona erdirme.",
    "Borçlar",
  ],
  [
    "TAKAS",
    "Karşılıklı ve aynı türden borçların kanuni şartlarla birbirini sona erdirmesi.",
    "Borçlar",
  ],
  ["TEMLİK", "Bir hak veya alacağın başka bir kişiye devredilmesi.", "Borçlar"],
  [
    "TEVDİ",
    "Bir şeyin korunmak veya teslim edilmek üzere yetkili yere bırakılması.",
    "Borçlar",
  ],
  [
    "RÜCU",
    "Ödeme yapanın koşulları varsa ilgili kişiden bu tutarı geri istemesi.",
    "Borçlar",
  ],
  [
    "İFLAS",
    "Borçlunun malvarlığının alacaklıların topluca tatmini için tasfiyesine ilişkin süreç.",
    "İcra",
  ],
  [
    "KONKORDATO",
    "Borçlunun alacaklılarla kanuni usulde anlaşarak borçlarını yapılandırması yolu.",
    "İcra",
  ],
  [
    "İCRA",
    "Bir hakkın yetkili organlar aracılığıyla zorla yerine getirilmesi.",
    "İcra",
  ],
  [
    "İHALE",
    "Bir mal veya işin belirlenen usulle teklif sahiplerinden birine verilmesi.",
    "Genel",
  ],
  [
    "ŞÜPHELİ",
    "Soruşturma aşamasında suç şüphesi altında bulunan kişi.",
    "Ceza",
  ],
  [
    "SANIK",
    "Kovuşturma başlayınca hükmün kesinleşmesine kadar suç isnadı altındaki kişi.",
    "Ceza",
  ],
  ["MAĞDUR", "İşlenen suçtan doğrudan zarar gören kişi.", "Ceza"],
  [
    "MÜŞTEKİ",
    "Suça ilişkin şikâyette bulunan kişinin yargılamadaki adı.",
    "Ceza",
  ],
  ["İHBAR", "Bir suç şüphesinin yetkili makamlara bildirilmesi.", "Ceza"],
  [
    "ŞİKAYET",
    "Suçtan zarar görenin ilgili fiil için soruşturma yapılmasını istemesi.",
    "Ceza",
  ],
  [
    "SORUŞTURMA",
    "Suç şüphesinin öğrenilmesinden iddianamenin kabulüne kadarki evre.",
    "Ceza",
  ],
  [
    "KOVUŞTURMA",
    "İddianamenin kabulünden hükmün kesinleşmesine kadarki ceza yargılaması evresi.",
    "Ceza",
  ],
  [
    "İDDİANAME",
    "Savcının suç isnadını ve delillerini açıklayarak kamu davası açılmasını istediği belge.",
    "Ceza",
  ],
  [
    "TUTUKLAMA",
    "Kanuni koşullarla kişinin hâkim kararıyla özgürlüğünün geçici sınırlandırılması.",
    "Ceza",
  ],
  [
    "GÖZALTI",
    "Yakalanan kişinin soruşturma için kanuni süre içinde tutulması.",
    "Ceza",
  ],
  [
    "YAKALAMA",
    "Suç şüphesi veya kanuni başka bir nedenle kişinin fiilen denetim altına alınması.",
    "Ceza",
  ],
  [
    "MÜSADERE",
    "Kanuni şartlarda bir eşyanın veya kazancın devlet mülkiyetine geçirilmesi.",
    "Ceza",
  ],
  [
    "TEŞEBBÜS",
    "Suçun icrasına başlanıp elde olmayan nedenlerle tamamlanamaması.",
    "Ceza",
  ],
  ["İŞTİRAK", "Bir suçun işlenmesine birden fazla kişinin katılması.", "Ceza"],
  ["AZMETTİRME", "Bir kişide suç işleme kararının oluşturulması.", "Ceza"],
  [
    "TEKERRÜR",
    "Önceki mahkûmiyetten sonra kanuni şartlarda yeniden suç işlenmesi.",
    "Ceza",
  ],
  [
    "İNFAZ",
    "Kesinleşen cezanın kanuni usule uygun yerine getirilmesi.",
    "Ceza",
  ],
  [
    "SAVUNMA",
    "Bir iddia veya suçlamaya karşı kişinin kendi görüş ve delillerini sunması.",
    "Genel",
  ],
  [
    "MÜDAFİ",
    "Ceza yargılamasında şüpheli veya sanığın savunmasını yapan avukat.",
    "Ceza",
  ],
  [
    "YÜRÜRLÜK",
    "Bir hukuk kuralının uygulanabilir olarak geçerli bulunduğu durum.",
    "Genel",
  ],
  [
    "ANAYASA",
    "Devletin temel yapısını ve temel hakları düzenleyen üstün hukuk metni.",
    "Anayasa",
  ],
  [
    "KANUN",
    "Yasama organınca anayasada öngörülen usulle kabul edilen genel düzenleme.",
    "Anayasa",
  ],
  [
    "YÖNETMELİK",
    "Kanunların uygulanmasını sağlamak üzere yetkili idarece çıkarılan düzenleme.",
    "İdare",
  ],
  [
    "İPTAL",
    "Bir hukuki işlemin geçerliliğinin yetkili karar veya iradeyle kaldırılması.",
    "Genel",
  ],
  [
    "KAMULAŞTIRMA",
    "Kamu yararı için özel mülkiyetteki taşınmazın kanuni usulle idarece edinilmesi.",
    "İdare",
  ],
] as const;
// Shown by the İpucu joker: a second angle on the term, not a repeat of the clue.
const hints: Record<string, string> = {
  DAVA: "Mahkemeye dilekçe verilerek açılır; sonunda hüküm kurulur.",
  DAVACI: "Mahkemeye ilk adımı atan, talebi ileri süren kişidir.",
  DAVALI: "Dilekçenin tebliğ edildiği, kendini savunan karşı taraftır.",
  HÜKÜM: "Duruşmanın sonunda okunur; kesinleşince uygulanabilir.",
  İLAM: "İcra dairesine götürülerek uygulamaya konabilen belgedir.",
  DURUŞMA: "Belirlenen gün ve saatte salonda yapılır; taraflar çağrılır.",
  DİLEKÇE: "Kurumlara ve mahkemelere imzalanarak verilen başvuru kâğıdıdır.",
  YETKİ: "Genel kural davalının yerleşim yeri mahkemesidir.",
  GÖREV: "Asliye hukuk mu, iş mahkemesi mi; sorusunun cevabını verir.",
  İSPAT: "'İddia eden kanıtlamak zorundadır' ilkesiyle bilinir.",
  KARİNE: "Aksi kanıtlanıncaya kadar doğru kabul edilen varsayımdır.",
  YEMİN:
    "Başka delil kalmadığında başvurulabilir; 'Namusum ve vicdanım üzerine…' diye başlar.",
  KEŞİF: "Hâkim gerekirse bilirkişiyle birlikte olay yerine gider.",
  ISLAH: "Dava boyunca yalnızca bir kez kullanılabilen bir düzeltme hakkıdır.",
  SULH: "Kelime anlamı barıştır; taraflar uzlaşınca dava biter.",
  TAHKİM: "Ticari uyuşmazlıklarda sık tercih edilen özel yargılama yoludur.",
  HAKEM: "Taraflarca seçilir; verdiği karar mahkeme kararı gibi bağlayıcıdır.",
  İTİRAZ: "Ödeme emrine yedi gün içinde yapılırsa takip durur.",
  MÜLKİYET: "Eşya üzerindeki en geniş haktır; sahibine malik denir.",
  PAYDAŞ: "Ortak taşınmazdaki hissesini tek başına satabilir.",
  İRTİFAK: "Komşu arazide geçit hakkı bunun bilinen bir örneğidir.",
  REHİN: "Borç ödenmezse eşya satılarak alacak karşılanır.",
  TAPU: "Ev alınca adınıza çıkarılan belge de bu adla anılır.",
  TESCİL: "Taşınmaz satışı ancak resmî kayda geçirilince tamamlanır.",
  TERKİN: "Borç ödenince ipoteğin kaldırılması bu işlemle olur.",
  ŞERH: "Kira sözleşmesi tapuya bu yolla işlenebilir.",
  KADASTRO: "Arazi ölçülür, haritası çizilir ve tapuya esas oluşturulur.",
  TAŞINMAZ: "Arsa, ev ve tarla bu gruptadır; satışı tapuda yapılır.",
  TAŞINIR: "Araba, mobilya ve para bu gruba girer.",
  İYİNİYET: "Medeni Kanuna göre varlığı asıl olarak kabul edilir.",
  EHLİYET:
    "Hak ve fiil olmak üzere ikiye ayrılır; sürücü belgesiyle karıştırılmasın.",
  ERGİNLİK:
    "On sekiz yaşın doldurulmasıyla başlar; evlenmek de bu sonucu doğurur.",
  GAİPLİK: "Kayıp kişinin ölü gibi sayılmasını sağlayan mahkeme kararıdır.",
  HISIMLIK: "Kan ve kayın olmak üzere iki türü vardır.",
  SOYBAĞI: "Babalık davası bu bağın kurulması için açılır.",
  NİŞANLANMA: "Evlilikten önceki aşamadır; yüzük takılması gelenektir.",
  BOŞANMA: "Anlaşmalı ya da çekişmeli olarak yürütülebilir.",
  TEREKE: "Mirasçılara kalan malların ve borçların toplamıdır.",
  MİRASÇI: "Kanuni ya da atanmış olabilir; reddetme hakkı vardır.",
  TENKİS: "Saklı payı zedelenen yakın akrabalar bu davayı açabilir.",
  EDİM: "Vermek, yapmak veya yapmamak şeklinde olabilir.",
  İFA: "Borcun sona ermesinin en olağan yoludur.",
  ALACAK: "Senede bağlanabilir, başkasına devredilebilir.",
  BORÇLU: "Edimi yerine getirmezse alacaklıya karşı sorumlu olur.",
  ALACAKLI: "İcra takibini başlatan taraftır.",
  SÖZLEŞME: "Öneri ve kabul birleşince kurulur.",
  İCAP: "Kabul edilirse sözleşme kurulur.",
  KABUL: "Öneriye 'evet' denmesidir; sözleşmeyi kurar.",
  HİLE: "Kandırılarak yapılan işlem bir yıl içinde iptal ettirilebilir.",
  MUVAZAA: "Mal kaçırmak için yapılan danışıklı satışlar buna örnektir.",
  BUTLAN: "Mutlak ve nisbi olmak üzere iki türü vardır.",
  FESİH: "Kira veya iş ilişkisini sona erdirmek için bildirilir.",
  TAKAS: "İki taraf birbirine borçluysa borçlar karşılıklı düşer.",
  TEMLİK: "Alacak devri de denir; yazılı şekilde yapılır.",
  TEVDİ:
    "Alacaklı parayı almazsa borçlu onu mahkemenin gösterdiği yere bırakır.",
  RÜCU: "Sigorta şirketi ödediği tazminatı kusurludan bu yolla ister.",
  İFLAS:
    "Tacirlerin borçlarını ödeyememesi hâlinde ticaret mahkemesince açılır.",
  KONKORDATO: "Mahkeme onayıyla borçlara vade ve indirim sağlanır.",
  İCRA: "Ödeme emri, haciz ve satış bu sürecin aşamalarıdır.",
  İHALE: "En uygun teklifi veren kazanır; kamu alımlarında başlıca yöntemdir.",
  ŞÜPHELİ: "İddianame kabul edilince sanık adını alır.",
  SANIK: "İddianamenin kabulünden sonra yargılanan kişinin sıfatıdır.",
  MAĞDUR: "Suçun doğrudan hedef aldığı kişidir; şikâyet hakkı vardır.",
  İHBAR: "Suçun mağduru olmayan herkes bu bildirimi yapabilir.",
  ŞİKAYET: "Bazı suçlarda soruşturma ancak mağdurun bu başvurusuyla başlar.",
  SORUŞTURMA: "Savcının yürüttüğü, delillerin toplandığı ilk evredir.",
  KOVUŞTURMA: "Mahkemede yürüyen, hükümle sona eren evredir.",
  İDDİANAME: "Kabul edilmesiyle kamu davası açılmış olur.",
  TUTUKLAMA:
    "Kaçma veya delil karartma şüphesi varsa sulh ceza hâkimi karar verir.",
  GÖZALTI: "Kural olarak yirmi dört saati geçemez.",
  YAKALAMA: "Suçüstü hâlinde herkes bu yetkiyi kullanabilir.",
  MÜSADERE: "Suçta kullanılan silah devlete geçirilebilir.",
  TEŞEBBÜS: "Suç tamamlanamazsa ceza indirilerek verilir.",
  İŞTİRAK: "Fail, azmettiren ve yardım eden bu kavramın türleridir.",
  TEKERRÜR: "Suçu tekrar işleyen kişiye özel infaz rejimi uygulanır.",
  İNFAZ: "Cezaevlerinde yürütülür; şartla tahliye de bu aşamaya aittir.",
  SAVUNMA: "Anayasal bir haktır; kimse dinlenmeden mahkûm edilemez.",
  MÜDAFİ: "Şüpheli istemese bile ağır suçlarda baro tarafından atanır.",
  YÜRÜRLÜK: "Kanunlar genellikle Resmî Gazete'de yayımlandığı gün başlar.",
  ANAYASA: "1982'de halkoyuyla kabul edilen metin bugün de geçerlidir.",
  KANUN: "TBMM'de kabul edilip Cumhurbaşkanınca yayımlanır.",
  YÖNETMELİK: "Bakanlıklar ve kamu tüzel kişilerince çıkarılabilir.",
  İPTAL: "Danıştay ve Anayasa Mahkemesi bu kararı verebilir.",
};
export const additionalQuestions: Question[] = rows.map(
  ([term, clue, category], i) => ({
    id: `v1q${i + 1}`,
    term,
    clue,
    explanation: hints[term] ?? clue,
    category,
    difficulty: term.length >= 9 ? 3 : 2,
  }),
);
