// The 80-bölüm campaign in ten-bölüm volumes. Volume 1 is all easy (four terms per bölüm).
// Volumes 2-8 each climb on their own: bölüm 1-4 easy (four terms), 5-7 medium (six terms),
// 8-9 hard (six terms) and a hard six-term final that revisits two terms of bölüm 8-9.
// Each tier is used in familiarity order, so later volumes are harder overall; the most
// familiar medium terms fill the easy bölüm of the last volumes. Written terms not listed
// here are kept in reserve and are not part of the game.
// Titles never contain an answer of their own bölüm (checked in tests).
export const campaignPlan: readonly { title: string | null; terms: readonly string[] }[] = [
  { title: "İlk İz", terms: ["KİŞİ", "DEVLET", "HAK", "KARAR"] },
  { title: "Kapıdaki Dosya", terms: ["AİLE", "GÖREV", "TAKİP", "ŞİRKET"] },
  { title: "Sessiz Tanık", terms: ["TARAF", "VARİS", "SANIK", "İFADE"] },
  { title: "Kayıp Anahtar", terms: ["SUÇ", "MAL", "KAYIT", "ÜCRET"] },
  { title: "Mühür Noktası", terms: ["DAVA", "CEZA", "ZARAR", "HUKUK"] },
  { title: "Gece Nöbeti", terms: ["İDDİA", "SATIŞ", "ADALET", "MAHKEME"] },
  { title: "Kırmızı Çizgi", terms: ["SAVUNMA", "HÜKÜMET", "KANUN", "İŞLEM"] },
  { title: "Yeni Deliller", terms: ["ALACAK", "İDARE", "SÖZLEŞME", "ÇEK"] },
  { title: "Terazi", terms: ["DEVİR", "ŞART", "İMZA", "ANAYASA"] },
  { title: null, terms: ["TERK", "KAMU", "ALACAK", "KUSUR", "ŞART", "İPTAL"] },
  { title: "Kişinin Hakları", terms: ["YEMİN", "MEMUR", "HAKİM", "TALEP"] },
  { title: "Ortak Masa", terms: ["BORÇ", "VERGİ", "VAKIF", "GÖZALTI"] },
  { title: "İkinci Celse", terms: ["YETKİ", "İSTİFA", "ARAZİ", "TANIK"] },
  { title: "Koridordaki Fısıltı", terms: ["SORUŞTURMA", "YARGI", "HAKEM", "HIRSIZ"] },
  { title: "Altın Kapı", terms: ["TEŞEBBÜS", "EHLİYET", "TELİF", "TAHSİS", "TASARRUF", "KARARNAME"] },
  { title: "Kâğıt İzleri", terms: ["TASARI", "FIKRA", "PARSEL", "FAİL", "ISLAH", "SULH"] },
  { title: "Ev Sahibi", terms: ["İFŞA", "MUHATAP", "UZLAŞMA", "ŞİKAYETÇİ", "HARÇ", "TEMYİZ"] },
  { title: "Çarşı Pazar", terms: ["İRAT", "YOKLUK", "EDA", "TEFSİR", "ACİZ", "MÜTEVELLİ"] },
  { title: "Son Söz", terms: ["DEFİ", "HASILAT", "ŞERH", "MÜDAHİL", "SAHİH", "TAHRİR"] },
  { title: null, terms: ["REPLİK", "MECRA", "İRAT", "HALEF", "HASILAT", "ZAYİ"] },
  { title: "Doğru Mahkeme", terms: ["ŞİKAYET", "SUÇLU", "HÜKÜM", "SAVCI"] },
  { title: "Tarafsız Bakış", terms: ["PAY", "MAHKUM", "VEKİL", "SORUMLULUK"] },
  { title: "Kasadaki Belge", terms: ["İTİRAZ", "ŞÜPHELİ", "SİGORTA", "DELİL"] },
  { title: "Sınır Taşları", terms: ["BAŞVURU", "MİRAS", "FAİZ", "CEZAEVİ"] },
  { title: "Kırk Yıllık Defter", terms: ["MÜEBBET", "EKLENTİ", "REŞİT", "MALİK", "KONTRAT", "İŞTİRAK"] },
  { title: "Aile Meclisi", terms: ["GASP", "YÖNETMELİK", "RUHSAT", "TEMİNAT", "TEBLİĞ", "TÜZEL"] },
  { title: "Veraset Defteri", terms: ["TAHSİL", "MENKUL", "TAŞINIR", "AKİT", "VASİYET", "SİCİL"] },
  { title: "Akdin Kurulması", terms: ["İCAZET", "TEKERRÜR", "FUZULİ", "TAHKİKAT", "MECUR", "İSNAT"] },
  { title: "Gizli Kusur", terms: ["AVAL", "HUSUMET", "EDİM", "FEZLEKE", "HASIM", "İSTİMLAK"] },
  { title: null, terms: ["İBRAZ", "İLAM", "İCAZET", "İKTİSAP", "HUSUMET", "İRTİFAK"] },
  { title: "Meclis Kürsüsü", terms: ["HAZİNE", "TAHLİYE", "TUTUKLU", "ŞAHİT"] },
  { title: "Liman Kenti", terms: ["İCRA", "MAĞDUR", "HİSSE", "DENETİM"] },
  { title: "Kalem Odası", terms: ["FATURA", "VELİ", "KİRA", "DİSİPLİN"] },
  { title: "Belediye Sarayı", terms: ["DURUŞMA", "ORTAKLIK", "ADLİYE", "SENET"] },
  { title: "Mühür Yeri", terms: ["ZİNA", "KOLLUK", "MÜDAFAA", "KATİP", "ŞAHSİYET", "FERAGAT"] },
  { title: "Ticaret Yolu", terms: ["İMTİYAZ", "İTHAM", "TAHKİM", "TÜZÜK", "FUHUŞ", "BEYANNAME"] },
  { title: "Fırtınalı Gün", terms: ["ERTELEME", "TASDİK", "VESAYET", "İDDİANAME", "NAFAKA", "RÜŞT"] },
  { title: "Uzun Koridor", terms: ["TEVDİ", "İNTİFA", "DONATAN", "TESELSÜL", "TEREKE", "NAVLUN"] },
  { title: "Karar Odası", terms: ["RESEN", "RÜCU", "MÜDAFİ", "TEMERRÜT", "ZIYA", "ZİLYET"] },
  { title: null, terms: ["MUACCEL", "TAHAKKUK", "TEVDİ", "TERKİN", "RÜCU", "TARH"] },
  { title: "Eski Arşiv", terms: ["İNFAZ", "MUHTAR", "TAZMİNAT", "MÜLK"] },
  { title: "Kubbe Altı", terms: ["İFLAS", "SORGU", "YARGITAY", "SAVCILIK"] },
  { title: "Zabıt Defteri", terms: ["YARGIÇ", "BOŞANMA", "GREV", "TUTUKLAMA"] },
  { title: "Kayıp Miras", terms: ["BORÇLU", "MÜHÜR", "BERAAT", "İFTİRA"] },
  { title: "Gölge Ortak", terms: ["HİBE", "KEFALET", "MUAFİYET", "MEVZUAT", "ZABITA", "TAAHHÜT"] },
  { title: "Ağır Dosya", terms: ["İCAP", "KAYYUM", "İLTİCA", "İPOTEK", "MÜTEAHHİT", "MUTABAKAT"] },
  { title: "Yüksek Kurul", terms: ["VETO", "DAVALI", "EMSAL", "VELAYET", "İNTİKAL", "HACİZ"] },
  { title: "Kıymetli Evrak", terms: ["MÜFLİS", "MAHSUP", "RİZİKO", "LEHTAR", "ZİLYETLİK", "MUVAFAKAT"] },
  { title: "Yeminli Söz", terms: ["TAKSİR", "İSTİHKAK", "KARİNE", "VAKIA", "MATRAH", "MÜTESELSİL"] },
  { title: null, terms: ["RAYİÇ", "İTFA", "MÜFLİS", "NİSAP", "İSTİHKAK", "KAMBİYO"] },
  { title: "Mürekkep Lekesi", terms: ["ZANLI", "TAPU", "DİLEKÇE", "ARSA"] },
  { title: "Kadim Kayıtlar", terms: ["NOTER", "GARDİYAN", "HÜKÜMLÜ", "KABUL"] },
  { title: "Kapalı Oturum", terms: ["HATA", "İFA", "ŞÜPHE", "TEMSİLCİ"] },
  { title: "Liman Defteri", terms: ["KATILAN", "İŞGAL", "TECAVÜZ", "USUL"] },
  { title: "Altın Terazi", terms: ["CEBİR", "SAYIŞTAY", "UYUŞMAZLIK", "MERA", "BİLİRKİŞİ", "DAVACI"] },
  { title: "Eski Hukuk", terms: ["BONO", "KADASTRO", "POLİÇE", "TACİR", "TAŞINMAZ", "İBRA"] },
  { title: "Sararmış Sayfalar", terms: ["VEKALET", "CİRO", "TUTANAK", "PAYDAŞ", "MÜVEKKİL", "MİRASÇI"] },
  { title: "Gizli Madde", terms: ["MÜCBİR", "CİRANTA", "MÜSADERE", "İSTİNABE", "RÜÇHAN", "TEAMÜL"] },
  { title: "Son Duruşma", terms: ["İKRAR", "TENKİS", "TEFHİM", "MÜMESSİL", "İSTİCVAP", "TEVSİK"] },
  { title: null, terms: ["İFRAZ", "İMTİNA", "MÜCBİR", "BUTLAN", "TENKİS", "GAİP"] },
  { title: "Ustanın İzi", terms: ["HAMİL", "İRADE", "İADE", "İHRAÇ"] },
  { title: "Derin Arşiv", terms: ["REFERANDUM", "KEŞİF", "TEŞHİS", "HİLE"] },
  { title: "Gümrük Kapısı", terms: ["İHLAL", "İHBAR", "TEDBİR", "YÜRÜRLÜK"] },
  { title: "Emanet Sandığı", terms: ["TAKSİM", "İHALE", "VADE", "KIYAS"] },
  { title: "Mühürlü Zarf", terms: ["MUHAKEME", "VERASET", "MURİS", "ALACAKLI", "MÜZAYEDE", "İSTİNAF"] },
  { title: "Kayıp Vakıf", terms: ["ZİMMET", "FESİH", "MÜKELLEF", "MUHTIRA", "KOVUŞTURMA", "İNTİHAL"] },
  { title: "Kâtibin Notu", terms: ["İHTAR", "VASİ", "DEPOZİTO", "MOBBİNG", "ZAMANAŞIMI", "TEBLİGAT"] },
  { title: "Dördüncü Celse", terms: ["HISIM", "MAHCUZ", "GAİPLİK", "TEDAVÜL", "TEMLİK", "TEVKİL"] },
  { title: "Büyük Gün", terms: ["MAKTU", "MUVAZAA", "TALİK", "HISIMLIK", "MÜTALAA", "YEDİEMİN"] },
  { title: null, terms: ["TADİL", "TRAMPA", "HISIM", "İVAZ", "MUVAZAA", "TAVZİH"] },
  { title: "Usta Kalem", terms: ["REHİN", "BATIL", "FİİL", "İHMAL"] },
  { title: "Eski Fermanlar", terms: ["İSPAT", "YAKALAMA", "TAHRİK", "EVRAK"] },
  { title: "Son Arşiv", terms: ["DEFİN", "TASFİYE", "HAVALE", "TAKAS"] },
  { title: "Kıyı Ticareti", terms: ["TESCİL", "İMAR", "MÜLKİYET", "KAST"] },
  { title: "Taç Mühür", terms: ["KONKORDATO", "İYİNİYET", "UZLAŞTIRMA", "SOYBAĞI", "LOKAVT", "ŞARTNAME"] },
  { title: "Kanunun Ruhu", terms: ["İLMÜHABER", "PAFTA", "MUKAVELE", "ONAMA", "İKAMETGAH", "AZİL"] },
  { title: "Altın Oran", terms: ["MAZBATA", "ACENTA", "İÇTİHAT", "MÜBAŞİR", "ERGİNLİK", "NİŞANLANMA"] },
  { title: "Mühürdar", terms: ["İSTİRDAT", "MÜKERRİR", "DERDEST", "MÜELLİF", "İLGA", "EMARE"] },
  { title: "Son Perde", terms: ["İRTİKAP", "TEBELLÜĞ", "MUHAMMEN", "HALEFİYET", "CELSE", "TAHKİK"] },
  { title: null, terms: ["MEHİL", "SİMSARLIK", "İSTİRDAT", "ÖNEL", "TEBELLÜĞ", "TEHİR"] },
];

// Difficulty from the familiarity ranking: 1 everyday, 2 needs some legal knowledge, 3 technical.
export const termDifficulty: Record<string, 1 | 2 | 3> = {
  "KİŞİ": 1, "DEVLET": 1, "HAK": 1, "KARAR": 1, "AİLE": 1, "GÖREV": 1, "TAKİP": 1, "ŞİRKET": 1,
  "TARAF": 1, "VARİS": 1, "SANIK": 1, "İFADE": 1, "SUÇ": 1, "MAL": 1, "KAYIT": 1, "ÜCRET": 1,
  "DAVA": 1, "CEZA": 1, "ZARAR": 1, "HUKUK": 1, "İDDİA": 1, "SATIŞ": 1, "ADALET": 1, "MAHKEME": 1,
  "SAVUNMA": 1, "HÜKÜMET": 1, "KANUN": 1, "İŞLEM": 1, "ALACAK": 1, "İDARE": 1, "SÖZLEŞME": 1,
  "ÇEK": 1, "DEVİR": 1, "ŞART": 1, "İMZA": 1, "ANAYASA": 1, "TERK": 1, "KAMU": 1, "KUSUR": 1,
  "İPTAL": 1, "YEMİN": 1, "MEMUR": 1, "HAKİM": 1, "TALEP": 1, "BORÇ": 1, "VERGİ": 1, "VAKIF": 1,
  "GÖZALTI": 1, "YETKİ": 1, "İSTİFA": 1, "ARAZİ": 1, "TANIK": 1, "SORUŞTURMA": 1, "YARGI": 1,
  "HAKEM": 1, "HIRSIZ": 1, "ŞİKAYET": 1, "SUÇLU": 1, "HÜKÜM": 1, "SAVCI": 1, "PAY": 1, "MAHKUM": 1,
  "VEKİL": 1, "SORUMLULUK": 1, "İTİRAZ": 1, "ŞÜPHELİ": 1, "SİGORTA": 1, "DELİL": 1, "BAŞVURU": 1,
  "MİRAS": 1, "FAİZ": 1, "CEZAEVİ": 1, "HAZİNE": 1, "TAHLİYE": 1, "TUTUKLU": 1, "ŞAHİT": 1,
  "İCRA": 1, "MAĞDUR": 1, "HİSSE": 1, "DENETİM": 1, "FATURA": 1, "VELİ": 1, "KİRA": 1,
  "DİSİPLİN": 1, "DURUŞMA": 1, "ORTAKLIK": 1, "ADLİYE": 1, "SENET": 1, "İNFAZ": 1, "MUHTAR": 1,
  "TAZMİNAT": 1, "MÜLK": 1, "İFLAS": 1, "SORGU": 1, "YARGITAY": 1, "SAVCILIK": 1, "YARGIÇ": 1,
  "BOŞANMA": 1, "GREV": 1, "TUTUKLAMA": 1, "BORÇLU": 1, "MÜHÜR": 1, "BERAAT": 1, "İFTİRA": 1,
  "ZANLI": 1, "TAPU": 1, "DİLEKÇE": 1, "ARSA": 1, "NOTER": 1, "GARDİYAN": 1, "HÜKÜMLÜ": 1,
  "KABUL": 2, "HATA": 2, "İFA": 2, "ŞÜPHE": 2, "TEMSİLCİ": 2, "KATILAN": 2, "İŞGAL": 2,
  "TECAVÜZ": 2, "USUL": 2, "HAMİL": 2, "İRADE": 2, "İADE": 2, "İHRAÇ": 2, "REFERANDUM": 2,
  "KEŞİF": 2, "TEŞHİS": 2, "HİLE": 2, "İHLAL": 2, "İHBAR": 2, "TEDBİR": 2, "YÜRÜRLÜK": 2,
  "TAKSİM": 2, "İHALE": 2, "VADE": 2, "KIYAS": 2, "REHİN": 2, "BATIL": 2, "FİİL": 2, "İHMAL": 2,
  "İSPAT": 2, "YAKALAMA": 2, "TAHRİK": 2, "EVRAK": 2, "DEFİN": 2, "TASFİYE": 2, "HAVALE": 2,
  "TAKAS": 2, "TESCİL": 2, "İMAR": 2, "MÜLKİYET": 2, "KAST": 2, "BEYAN": 2, "TEŞEBBÜS": 2,
  "EHLİYET": 2, "TELİF": 2, "TAHSİS": 2, "TASARRUF": 2, "KARARNAME": 2, "TASARI": 2, "FIKRA": 2,
  "PARSEL": 2, "FAİL": 2, "ISLAH": 2, "SULH": 2, "İFŞA": 2, "MUHATAP": 2, "UZLAŞMA": 2,
  "ŞİKAYETÇİ": 2, "HARÇ": 2, "TEMYİZ": 2, "MÜEBBET": 2, "EKLENTİ": 2, "REŞİT": 2, "MALİK": 2,
  "KONTRAT": 2, "İŞTİRAK": 2, "GASP": 2, "YÖNETMELİK": 2, "RUHSAT": 2, "TEMİNAT": 2, "TEBLİĞ": 2,
  "TÜZEL": 2, "TAHSİL": 2, "MENKUL": 2, "TAŞINIR": 2, "AKİT": 2, "VASİYET": 2, "SİCİL": 2,
  "ZİNA": 2, "KOLLUK": 2, "MÜDAFAA": 2, "KATİP": 2, "ŞAHSİYET": 2, "FERAGAT": 2, "İMTİYAZ": 2,
  "İTHAM": 2, "TAHKİM": 2, "TÜZÜK": 2, "FUHUŞ": 2, "BEYANNAME": 2, "ERTELEME": 2, "TASDİK": 2,
  "VESAYET": 2, "İDDİANAME": 2, "NAFAKA": 2, "RÜŞT": 2, "HİBE": 2, "KEFALET": 2, "MUAFİYET": 2,
  "MEVZUAT": 2, "ZABITA": 2, "TAAHHÜT": 2, "İCAP": 2, "KAYYUM": 2, "İLTİCA": 2, "İPOTEK": 2,
  "MÜTEAHHİT": 2, "MUTABAKAT": 2, "VETO": 2, "DAVALI": 2, "EMSAL": 2, "VELAYET": 2, "İNTİKAL": 2,
  "HACİZ": 2, "CEBİR": 2, "SAYIŞTAY": 2, "UYUŞMAZLIK": 2, "MERA": 2, "BİLİRKİŞİ": 2, "DAVACI": 2,
  "BONO": 2, "KADASTRO": 2, "POLİÇE": 2, "TACİR": 2, "TAŞINMAZ": 2, "İBRA": 2, "VEKALET": 2,
  "CİRO": 2, "TUTANAK": 2, "PAYDAŞ": 2, "MÜVEKKİL": 2, "MİRASÇI": 2, "MUHAKEME": 2, "VERASET": 2,
  "MURİS": 2, "ALACAKLI": 2, "MÜZAYEDE": 2, "İSTİNAF": 2, "ZİMMET": 2, "FESİH": 2, "MÜKELLEF": 2,
  "MUHTIRA": 2, "KOVUŞTURMA": 2, "İNTİHAL": 2, "İHTAR": 2, "VASİ": 2, "DEPOZİTO": 2, "MOBBİNG": 2,
  "ZAMANAŞIMI": 2, "TEBLİGAT": 2, "KONKORDATO": 2, "İYİNİYET": 2, "UZLAŞTIRMA": 2, "SOYBAĞI": 2,
  "LOKAVT": 2, "ŞARTNAME": 2, "İLMÜHABER": 2, "PAFTA": 2, "MUKAVELE": 2, "ONAMA": 2,
  "İKAMETGAH": 2, "AZİL": 2, "MAZBATA": 2, "ACENTA": 2, "İÇTİHAT": 2, "MÜBAŞİR": 2, "ERGİNLİK": 2,
  "NİŞANLANMA": 2, "MAKTUL": 2, "GENSORU": 2, "PARAF": 2, "DOKTRİN": 2, "OMBUDSMAN": 2,
  "DEVREMÜLK": 2,
  "İRAT": 3, "YOKLUK": 3, "EDA": 3, "TEFSİR": 3, "ACİZ": 3, "MÜTEVELLİ": 3, "DEFİ": 3,
  "HASILAT": 3, "ŞERH": 3, "MÜDAHİL": 3, "SAHİH": 3, "TAHRİR": 3, "REPLİK": 3, "MECRA": 3,
  "HALEF": 3, "ZAYİ": 3, "İCAZET": 3, "TEKERRÜR": 3, "FUZULİ": 3, "TAHKİKAT": 3, "MECUR": 3,
  "İSNAT": 3, "AVAL": 3, "HUSUMET": 3, "EDİM": 3, "FEZLEKE": 3, "HASIM": 3, "İSTİMLAK": 3,
  "İBRAZ": 3, "İLAM": 3, "İKTİSAP": 3, "İRTİFAK": 3, "TEVDİ": 3, "İNTİFA": 3, "DONATAN": 3,
  "TESELSÜL": 3, "TEREKE": 3, "NAVLUN": 3, "RESEN": 3, "RÜCU": 3, "MÜDAFİ": 3, "TEMERRÜT": 3,
  "ZIYA": 3, "ZİLYET": 3, "MUACCEL": 3, "TAHAKKUK": 3, "TERKİN": 3, "TARH": 3, "MÜFLİS": 3,
  "MAHSUP": 3, "RİZİKO": 3, "LEHTAR": 3, "ZİLYETLİK": 3, "MUVAFAKAT": 3, "TAKSİR": 3,
  "İSTİHKAK": 3, "KARİNE": 3, "VAKIA": 3, "MATRAH": 3, "MÜTESELSİL": 3, "RAYİÇ": 3, "İTFA": 3,
  "NİSAP": 3, "KAMBİYO": 3, "MÜCBİR": 3, "CİRANTA": 3, "MÜSADERE": 3, "İSTİNABE": 3, "RÜÇHAN": 3,
  "TEAMÜL": 3, "İKRAR": 3, "TENKİS": 3, "TEFHİM": 3, "MÜMESSİL": 3, "İSTİCVAP": 3, "TEVSİK": 3,
  "İFRAZ": 3, "İMTİNA": 3, "BUTLAN": 3, "GAİP": 3, "HISIM": 3, "MAHCUZ": 3, "GAİPLİK": 3,
  "HISIMLIK": 3, "TEMLİK": 3, "TEVKİL": 3, "MAKTU": 3, "MUVAZAA": 3, "TALİK": 3, "TEDAVÜL": 3,
  "MÜTALAA": 3, "YEDİEMİN": 3, "TADİL": 3, "TRAMPA": 3, "İVAZ": 3, "TAVZİH": 3, "İSTİRDAT": 3,
  "MÜKERRİR": 3, "DERDEST": 3, "MÜELLİF": 3, "İLGA": 3, "EMARE": 3, "İRTİKAP": 3, "TEBELLÜĞ": 3,
  "MUHAMMEN": 3, "HALEFİYET": 3, "CELSE": 3, "TAHKİK": 3, "MEHİL": 3, "SİMSARLIK": 3, "ÖNEL": 3,
  "TEHİR": 3, "MERHUN": 3, "MÜEYYİDE": 3, "MÜTEMERRİT": 3, "İNFİSAH": 3, "İMHAL": 3, "İZALE": 3,
  "TASHİH": 3, "TEDİYE": 3, "VARAKA": 3, "İHTARNAME": 3, "SAİK": 3, "TECİL": 3, "TEVKİF": 3,
  "FERAĞ": 3, "İCBAR": 3, "TENSİP": 3, "TENFİZ": 3, "TAHKİR": 3, "TAKYİT": 3, "MAZNUN": 3,
  "ŞİFAHİ": 3, "İSTİNKAF": 3, "ECRİMİSİL": 3, "MÜZEKKERE": 3, "NEMA": 3, "İSKAT": 3, "CÜRÜM": 3,
  "TEVZİ": 3, "TEMETTÜ": 3, "TECZİYE": 3, "ALENİYET": 3, "MÜKTESEP": 3, "İCAR": 3, "NESEP": 3,
  "SÜKNA": 3, "ANTREPO": 3, "CELPNAME": 3, "MÜRTEHİN": 3, "SUİNİYET": 3, "AZMETTİRME": 3,
  "GASIB": 3, "İKRAZ": 3, "VEDİA": 3, "BAĞIT": 3, "KEŞİDE": 3, "DESİSE": 3, "MÜDDEİ": 3,
  "MÜŞTEKİ": 3, "İLTİMAS": 3, "ARZUHAL": 3, "İBRANAME": 3, "GAYBUBET": 3, "EHLİVUKUF": 3,
  "MÜŞTEMİLAT": 3, "KABZ": 3, "ŞUFA": 3, "GABİN": 3, "HACİR": 3, "İKALE": 3, "İTLAF": 3,
  "SEMEN": 3, "İKRAH": 3, "LAYİHA": 3, "TERHİN": 3, "ARİYET": 3, "TÖHMET": 3, "VAKFİYE": 3,
  "MAMELEK": 3, "TAAMMÜT": 3, "TEBERRU": 3, "KEŞİDECİ": 3, "MÜSTECİR": 3, "PLEBİSİT": 3,
  "MALPRAKTİS": 3, "TEMLİKNAME": 3,
};
