// New campaign terms (easy and medium). Each row: term, clue, hint shown by the İpucu joker,
// category. Terms that already existed keep their original question and id in content.ts.
export type WordRow = readonly [term: string, clue: string, hint: string, category: string];

export const easyRows: readonly WordRow[] = [
  ["KİŞİ", "Hak ve borçlara sahip olabilen gerçek veya tüzel varlık.", "İnsan da şirket de hukuken bu sıfatı taşıyabilir.", "Medeni"],
  ["DEVLET", "Belirli bir ülkede egemenlik kuran, halk ve topraktan oluşan siyasi ve hukuki örgüt.", "Ülke, halk ve egemenlik onun üç temel unsurudur.", "Anayasa"],
  ["HAK", "Hukuk düzeninin kişiye tanıdığı ve koruduğu yetki.", "Mahkemede aranan, korunan şeydir; karşılığında bir yükümlülük bulunur.", "Genel"],
  ["KARAR", "Mahkemenin veya yetkili bir makamın bir konuda verdiği sonuç.", "Duruşmanın sonunda okunur; itiraz veya temyiz edilebilir.", "Usul"],
  ["AİLE", "Evlilik ve kan bağı üzerine kurulan, kanunla korunan temel toplum birimi.", "Anayasa onu toplumun temeli sayar.", "Aile"],
  ["TAKİP", "Bir alacağın icra dairesi aracılığıyla zorla tahsili için başlatılan süreç.", "Ödeme emriyle başlar.", "İcra"],
  ["ŞİRKET", "Ortak bir amaca ulaşmak için emek veya sermayesini birleştiren kişilerin kurduğu ortaklık.", "Anonim ve limitet en bilinen türleridir.", "Ticaret"],
  ["TARAF", "Bir sözleşmede veya davada hak ve yükümlülük sahibi olan kişi.", "Davada davacı ve davalı bu sıfatı taşır.", "Usul"],
  ["VARİS", "Ölen bir kişinin mirası üzerinde hak sahibi olan kişi.", "Mirasçı ile aynı anlama gelir.", "Miras"],
  ["İFADE", "Şüphelinin, tanığın veya mağdurun yetkili makama anlattıkları ve bunun kayda geçirilmesi.", "Karakolda veya savcılıkta alınır.", "Ceza"],
  ["SUÇ", "Kanunun açıkça yasakladığı ve karşılığında ceza öngördüğü eylem.", "Kanunsuz ceza olmaz; bu eylem de kanunla belirlenir.", "Ceza"],
  ["MAL", "Kişinin sahip olabileceği, taşınır veya taşınmaz her türlü değer.", "Ev, araba ve para bunun örnekleridir.", "Eşya"],
  ["KAYIT", "Bir bilginin resmî bir deftere veya sicile yazılması.", "Nüfus ya da tapu dairesinde yapılır.", "İdare"],
  ["ÜCRET", "Bir işin veya hizmetin karşılığı olarak ödenen para.", "İşçinin emeği karşılığında aldığı ödemedir.", "İş"],
  ["CEZA", "Suç işleyen kişiye kanun gereği uygulanan yaptırım.", "Hapis ve adli para bunun türleridir.", "Ceza"],
  ["ZARAR", "Kişinin malvarlığında veya kişilik değerlerinde istemeden meydana gelen eksilme.", "Tazminatla giderilmesi istenir.", "Borçlar"],
  ["HUKUK", "Toplumsal düzeni sağlayan ve devlet gücüyle desteklenen kurallar bütünü.", "Adalet fakülteleri bu bilimi öğretir.", "Genel"],
  ["İDDİA", "Bir taraf veya savcı tarafından doğru olduğu ileri sürülen ve ispatı gereken husus.", "Mahkemede delille desteklenmesi gerekir.", "Usul"],
  ["SATIŞ", "Satıcının malın mülkiyetini, alıcının da bedelini ödemeyi üstlendiği işlem.", "En sık yapılan sözleşme türüdür.", "Borçlar"],
  ["ADALET", "Herkese hakkını verme ve hakka uygun davranma ilkesi.", "Mahkeme salonlarında 'mülkün temeli' olarak yazar.", "Genel"],
  ["MAHKEME", "Uyuşmazlıkları ve suçları kanuna göre karara bağlayan bağımsız yargı organı.", "Hâkimlerin görev yaptığı yerdir.", "Usul"],
  ["HÜKÜMET", "Devletin yürütme işlerini yöneten organ.", "Bakanlar bu organın üyesidir.", "Anayasa"],
  ["İŞLEM", "Hukuki sonuç doğurmak amacıyla yapılan irade açıklaması.", "Sözleşme ve vasiyet bunun örnekleridir.", "Genel"],
  ["İDARE", "Kamu hizmetlerini yürüten devlet örgütü ve bu örgütün faaliyeti.", "Bakanlıklar ve belediyeler bu yapının parçasıdır.", "İdare"],
  ["ÇEK", "Bankadaki hesaptan, ibraz edildiğinde ödenmesi için verilen yazılı ödeme emri.", "Karşılıksız çıkması ciddi sonuç doğurur.", "Ticaret"],
  ["DEVİR", "Bir hakkın veya borcun bir kişiden başka bir kişiye geçirilmesi.", "Tapuda mülk el değiştirirken de yapılır.", "Borçlar"],
  ["ŞART", "Bir işlemin sonucunu, gerçekleşip gerçekleşmeyeceği belli olmayan bir olaya bağlayan kayıt.", "Geciktirici veya bozucu olabilir.", "Borçlar"],
  ["İMZA", "Kişinin bir belgeyi kabul ettiğini göstermek için kendi eliyle koyduğu işaret.", "Senedin altına atılır.", "Genel"],
  ["TERK", "Bir hakkın, malın veya kişinin bırakılıp ondan vazgeçilmesi.", "Eşin evi bu şekilde bırakması boşanma sebebidir.", "Aile"],
  ["KAMU", "Devlet ve ona bağlı tüzel kişiler; toplumun bütünü.", "Bu yararı gözeten işlemler özel çıkarın önüne geçer.", "İdare"],
  ["KUSUR", "Hukuka aykırı bir sonucu isteyerek ya da gereken özeni göstermeyerek doğurma.", "Tazminat sorumluluğunun temel şartlarından biridir.", "Borçlar"],
  ["MEMUR", "Kamu hizmetinin asli ve sürekli görevlerini yürütmek üzere atanan kişi.", "Devlet dairesinde çalışır.", "İdare"],
  ["HAKİM", "Mahkemede yargılama yapıp karar veren yargı mensubu.", "Cübbe giyer, kürsüde oturur.", "Usul"],
  ["TALEP", "Bir hakkın veya bir işlemin yetkili makamdan istenmesi.", "Dilekçede açıkça yazılması gerekir.", "Usul"],
  ["BORÇ", "Bir kişinin, alacaklıya karşı belirli bir edimi yerine getirme yükümlülüğü.", "Alacağın karşı yüzüdür.", "Borçlar"],
  ["VERGİ", "Devletin kamu giderleri için kanuna dayanarak kişilerden aldığı karşılıksız para.", "Gelir ve KDV bunun türleridir.", "Vergi"],
  ["VAKIF", "Bir malvarlığının belirli bir amaca sürekli olarak özgülenmesiyle kurulan tüzel kişi.", "Hayır işleri için kurulur.", "Medeni"],
  ["İSTİFA", "Kişinin kendi isteğiyle bir görevden ayrılması.", "Dilekçeyle bildirilir.", "İş"],
  ["ARAZİ", "Üzerinde yapı bulunmayan, ekilebilen ya da boş toprak parçası.", "Tarla da bu kapsamdadır.", "Eşya"],
  ["YARGI", "Hukuk kurallarının bağımsız mahkemelerce somut olaylara uygulanması yetkisi.", "Yasama ve yürütme ile birlikte üç güçten biridir.", "Anayasa"],
  ["HIRSIZ", "Başkasının taşınır malını rızası olmadan alan kişi.", "Gizlice ve izinsiz alır.", "Ceza"],
  ["SUÇLU", "Suç işlediği mahkeme kararıyla sabit olan kişi.", "Masumiyet karinesi bu sıfatı kesin hükme bağlar.", "Ceza"],
  ["SAVCI", "Kamu adına soruşturma yapan ve dava açan yargı mensubu.", "İddianameyi o hazırlar.", "Ceza"],
  ["PAY", "Ortak bir mal veya hak üzerinde her bir hak sahibine düşen oran.", "Kesirle gösterilir: yarım, üçte bir gibi.", "Eşya"],
  ["MAHKUM", "Hakkında hapis cezasına hükmedilmiş kişi.", "Cezasını infaz kurumunda çeker.", "Ceza"],
  ["VEKİL", "Başkası adına ve hesabına iş gören, onu temsil eden kişi.", "Avukat da müvekkilinin böyle temsilcisidir.", "Borçlar"],
  ["SORUMLULUK", "Kişinin bir eyleminin veya yükümlülüğünün hukuki sonuçlarına katlanması.", "Kusurlu olan bunu üstlenir.", "Borçlar"],
  ["SİGORTA", "Prim karşılığında olası bir riskin doğuracağı zararın güvence altına alınması.", "Kasko ve trafik poliçesi bunun örnekleridir.", "Ticaret"],
  ["BAŞVURU", "Bir hakkın korunması veya bir işlemin yapılması için yetkili makama müracaat.", "Anayasa Mahkemesine bireysel olarak da yapılabilir.", "Usul"],
  ["FAİZ", "Paranın kullanılması karşılığında veya geç ödenmesi nedeniyle ödenen bedel.", "Gecikmede temerrüt türü işler.", "Borçlar"],
  ["CEZAEVİ", "Hükümlü ve tutukluların kaldığı ceza infaz kurumu.", "Halk arasında hapishane denir.", "Ceza"],
  ["HAZİNE", "Devletin mallarını ve parasal varlığını temsil eden kamu tüzel kişiliği.", "Sahipsiz taşınmazlar ona kalır.", "İdare"],
  ["TUTUKLU", "Hakkında tutuklama kararı verilmiş, hürriyeti kısıtlanmış kişi.", "Henüz kesin hüküm giymemiştir.", "Ceza"],
  ["ŞAHİT", "Bir olayı gördüğünü veya duyduğunu mahkemede anlatan kişi.", "Tanık ile aynı anlama gelir.", "Usul"],
  ["HİSSE", "Ortak bir mal veya sermaye üzerinde kişiye düşen pay.", "Borsada da alınıp satılır.", "Ticaret"],
  ["DENETİM", "Bir işlem veya faaliyetin hukuka ve kurallara uygunluğunun incelenmesi.", "İdarenin işlemleri yargısal olarak da incelenir.", "İdare"],
  ["FATURA", "Satılan mal veya yapılan iş karşılığında alıcıya verilen ve borcu gösteren belge.", "Vergi açısından düzenlenmesi zorunludur.", "Vergi"],
  ["VELİ", "Ergin olmayan çocuğun velayet hakkına sahip annesi veya babası.", "Okul kayıtlarında da imzası istenir.", "Aile"],
  ["KİRA", "Bir şeyin kullanılmasının belirli bir bedel karşılığında başkasına bırakılması.", "Ev sahibine her ay ödenir.", "Borçlar"],
  ["DİSİPLİN", "Kurum düzenini korumak için konulan kurallar ve aykırılığa uygulanan yaptırımlar.", "Memura uyarma veya kınama cezası verilebilir.", "İdare"],
  ["ORTAKLIK", "Birden çok kişinin bir mal, hak veya iş üzerinde birlikte hak sahibi olması.", "Evlilikte mal rejimi olarak da seçilebilir.", "Eşya"],
  ["ADLİYE", "Mahkemelerin ve savcılıkların bulunduğu yargı binası.", "Duruşmalar orada görülür.", "Usul"],
  ["SENET", "Bir borcu veya hukuki ilişkiyi gösteren imzalı yazılı belge.", "Bono da bunun bir türüdür.", "Borçlar"],
  ["MUHTAR", "Köy veya mahallenin seçilmiş yöneticisi.", "İkametgâh belgesini o verir.", "İdare"],
  ["MÜLK", "Bir kişinin sahip olduğu mal, özellikle taşınmaz.", "Tapuda adına kayıtlıdır.", "Eşya"],
  ["SORGU", "Hâkimin sanığa olayla ilgili sorular yöneltmesi ve cevaplarını alması.", "Kovuşturma evresinde yapılır.", "Ceza"],
  ["YARGITAY", "Adli yargıda ilk derece ve istinaf kararlarını inceleyen en yüksek mahkeme.", "Ankara'dadır; kararları içtihat oluşturur.", "Usul"],
  ["SAVCILIK", "Kamu adına soruşturma yürüten ve kamu davası açan makam.", "Suç duyurusu buraya yapılır.", "Ceza"],
  ["YARGIÇ", "Mahkemede yargılama yapıp karar veren kişi.", "Öz Türkçe karşılığıdır; hâkim ile eş anlamlıdır.", "Usul"],
  ["GREV", "İşçilerin işverene karşı topluca ve birlikte iş bırakması.", "Sendikal haklardandır.", "İş"],
  ["MÜHÜR", "Bir belgeyi veya eşyayı onaylamak ya da korumak için basılan resmî damga.", "Bu oyunun adı da odur.", "Genel"],
  ["İFTİRA", "Suçsuz olduğunu bildiği birini suç işlemiş gibi yetkili makama ihbar etme.", "Kendisi de suçtur.", "Ceza"],
  ["ZANLI", "Hakkında suç işlediği şüphesi bulunan kişi.", "Şüpheli veya sanık için halk arasında kullanılır.", "Ceza"],
  ["ARSA", "İmar planı içinde, üzerine yapı yapılmak üzere ayrılmış toprak parçası.", "Kat karşılığı müteahhide verilebilir.", "Eşya"],
  ["NOTER", "Belge ve işlemlere resmî geçerlik kazandıran kamu görevlisi.", "Araç satışı ve vekâletname onun önünde yapılır.", "Genel"],
  ["GARDİYAN", "Ceza infaz kurumunda düzeni ve güvenliği sağlayan görevli.", "Koğuşları o denetler.", "Ceza"],
  ["HÜKÜMLÜ", "Hakkındaki mahkûmiyet kararı kesinleşmiş kişi.", "Tutukludan farkı kararının kesinleşmiş olmasıdır.", "Ceza"],
  ["HATA", "Bir işlemi yaparken gerçeğe aykırı bir düşünceyle yanılma.", "Esaslı olanı sözleşmeyi iptal ettirebilir.", "Borçlar"],
  ["ŞÜPHE", "Bir olayın gerçekleştiği konusunda kesinlik bulunmayan kanaat.", "Sanık lehine yorumlanır.", "Ceza"],
  ["TEMSİLCİ", "Başkası adına ve onun hesabına hareket etme yetkisi olan kişi.", "Yaptığı işlemin sonucu temsil edilene bağlanır.", "Borçlar"],
  ["KATILAN", "Kamu davasına mağdur sıfatıyla dahil olan kişi.", "Ceza davasında savcının yanında yer alır.", "Ceza"],
  ["İŞGAL", "Başkasına ait bir yeri izinsiz ve haksız olarak kullanma.", "Elatmanın önlenmesi davasıyla sona erdirilir.", "Eşya"],
  ["TECAVÜZ", "Bir hakka veya kişiye karşı yapılan hukuka aykırı saldırı.", "Kişilik hakkına yapılırsa dava açılabilir.", "Ceza"],
  ["USUL", "Hakların mahkemede nasıl aranacağını düzenleyen şekil kuralları.", "Esasın karşıtıdır; süre ve şekle ilişkindir.", "Usul"],
  ["HAMİL", "Kıymetli bir evrakı elinde bulunduran ve ondan hak talep edebilen kişi.", "Çeki bankaya o ibraz eder.", "Ticaret"],
  ["İRADE", "Kişinin belirli bir hukuki sonuç doğurmaya yönelik iç isteği.", "Sözleşmede tarafların bu açıklamaları uyuşmalıdır.", "Borçlar"],
  ["İADE", "Alınan bir şeyin sahibine geri verilmesi.", "Ayıplı malda tüketicinin seçimlik haklarındandır.", "Borçlar"],
  ["İHRAÇ", "Bir kişinin üyesi olduğu kurum veya meslekten çıkarılması.", "En ağır disiplin cezalarındandır.", "İdare"],
  ["REFERANDUM", "Bir konunun doğrudan halkın oyuna sunulması.", "Anayasa değişiklikleri için yapılabilir.", "Anayasa"],
  ["TEŞHİS", "Bir kişinin kim olduğunun tanınarak belirlenmesi.", "Şüpheli sıra halinde dizilerek gösterilebilir.", "Ceza"],
  ["İHLAL", "Bir hakkın, kuralın veya yükümlülüğün çiğnenmesi.", "Sözleşmeye aykırılık da bunun bir örneğidir.", "Genel"],
  ["TEDBİR", "Bir hakkın korunması için dava sonuçlanmadan alınan geçici önlem.", "İhtiyati olanı uyuşmazlık konusunun durumunu korur.", "Usul"],
  ["TAKSİM", "Ortak mülkiyetteki bir malın ortaklar arasında bölüştürülmesi.", "Anlaşamazlarsa ortaklığın giderilmesi davası açılır.", "Eşya"],
  ["VADE", "Bir borcun ödenmesi gereken tarih.", "Geldiğinde borç muaccel olur.", "Borçlar"],
  ["KIYAS", "Hakkında hüküm bulunmayan bir olaya benzer olayın kuralını uygulama.", "Ceza hukukunda aleyhe olanı yasaktır.", "Genel"],
  ["BATIL", "Hukuken hiç doğmamış sayılan, geçersiz.", "Kesin hükümsüzlükle aynı sonucu doğurur.", "Borçlar"],
  ["FİİL", "Hukuki sonuç doğuran insan davranışı; eylem.", "Haksız olanı tazminat doğurur.", "Genel"],
  ["İHMAL", "Gereken özeni göstermeyerek bir yükümlülüğü yerine getirmeme.", "Görevi bu şekilde savsaklamak suç olabilir.", "Ceza"],
  ["TAHRİK", "Bir kişiyi haksız bir davranışla öfkelendirip harekete geçirme.", "Haksız olanı cezada indirim sebebidir.", "Ceza"],
  ["EVRAK", "Resmî işlemlerde kullanılan yazılı belgeler.", "Kıymetli olanları çek ve bonodur.", "Genel"],
  ["DEFİN", "Ölünün kanuni usule uygun olarak gömülmesi.", "İzinsiz yapılması suçtur.", "İdare"],
  ["TASFİYE", "Sona eren bir şirketin alacak ve borçlarının ödenerek kapatılması.", "Bunu yürüten kişiye memur denir.", "Ticaret"],
  ["HAVALE", "Bir kişinin başkasına, kendi hesabına ödeme yapması için verdiği talimat.", "Bankadan para göndermek de buna benzer.", "Borçlar"],
  ["İMAR", "Kentlerde yapılaşmanın plana ve kurallara göre düzenlenmesi.", "Belediye bu planla yapı izni verir.", "İdare"],
  ["BEYAN", "Bir kişinin bir hususu sözlü veya yazılı olarak açıkça bildirmesi.", "Vergide gelir bu şekilde bildirilir.", "Genel"],
  ["TELİF", "Bir eserin sahibine tanınan maddi ve manevi haklar.", "Yazarlar ve besteciler bu ücreti alır.", "Ticaret"],
  ["TAHSİS", "Bir malın veya hakkın belirli bir kişiye ya da amaca ayrılması.", "Lojman bu şekilde memura ayrılır.", "İdare"],
  ["TASARRUF", "Bir hak üzerinde devir, sınırlama veya vazgeçme gibi doğrudan etki eden işlem.", "Ölüme bağlı olanı vasiyettir.", "Medeni"],
  ["KARARNAME", "Yürütme organı tarafından çıkarılan ve hukuki sonuç doğuran yazılı düzenleme.", "Cumhurbaşkanlığı tarafından da çıkarılır.", "Anayasa"],
  ["TASARI", "Meclise sunulan ve henüz kanunlaşmamış metin.", "Kabul edilirse kanun olur.", "Anayasa"],
  ["FIKRA", "Bir kanun maddesini oluşturan ve ayrı paragraf hâlindeki bölümlerden her biri.", "Madde, bu bölümler ve bentlerden oluşur.", "Genel"],
  ["PARSEL", "Kadastroda sınırları belirlenmiş arazi parçalarından her biri.", "Tapuda ada numarasıyla birlikte yazılır.", "Eşya"],
  ["FAİL", "Suçu işleyen kişi.", "Suçun mağdurunun karşısındaki kişidir.", "Ceza"],
  ["İFŞA", "Gizli kalması gereken bir bilginin açığa vurulması.", "Sır saklama yükümlülüğüne aykırıdır.", "Ceza"],
  ["MUHATAP", "Bir işlemin veya bildirimin kendisine yöneltildiği kişi.", "Çekte ödemeyi yapacak banka bu sıfattadır.", "Genel"],
  ["UZLAŞMA", "Tarafların karşılıklı anlaşarak bir uyuşmazlığı sona erdirmesi.", "Vergi idaresiyle de yapılabilir.", "Genel"],
  ["ŞİKAYETÇİ", "Suçtan zarar görüp failin cezalandırılmasını isteyen kişi.", "Müşteki ile aynı anlama gelir.", "Ceza"],
  ["HARÇ", "Kamu hizmetinden yararlananlardan kanuna göre alınan bedel.", "Dava açarken mahkeme veznesine yatırılır.", "Vergi"],
  ["MÜEBBET", "Süresiz, ömür boyu süren.", "En ağır hapis cezası bu niteliktedir.", "Ceza"],
  ["EKLENTİ", "Asıl şeye sürekli olarak bağlanmış, onun işine yarayan yardımcı şey.", "Evin bahçesi ve garajı bunun örneğidir.", "Eşya"],
  ["REŞİT", "On sekiz yaşını doldurmuş, ergin.", "Bu yaştan sonra kişi kendi işlemlerini yapabilir.", "Medeni"],
  ["MALİK", "Bir malın mülkiyet hakkına sahip olan kişi.", "Tapuda adı yazan kişidir.", "Eşya"],
  ["KONTRAT", "Kira veya benzeri işler için yapılan yazılı sözleşme.", "Halk arasında ev kiralarken imzalanır.", "Borçlar"],
  ["GASP", "Başkasının malını zor kullanarak alma.", "Yağma suçunun halk arasındaki adıdır.", "Ceza"],
  ["RUHSAT", "Bir faaliyet için yetkili makamca verilen izin ve bunu gösteren belge.", "Yapı ve silah için alınır.", "İdare"],
  ["TEMİNAT", "Bir borcun ödenmesini güvence altına almak için verilen değer.", "İpotek ve rehin bunun türleridir.", "Borçlar"],
  ["TEBLİĞ", "Bir belgenin veya kararın usulüne uygun olarak ilgilisine bildirilmesi.", "Süreler bu bildirimden itibaren işler.", "Usul"],
  ["TÜZEL", "Gerçek kişi olmayıp kanunla kişilik tanınan topluluk veya mal varlığı için kullanılan sıfat.", "Şirketler ve dernekler bu niteliktedir.", "Medeni"],
  ["TAHSİL", "Bir alacağın veya verginin borçludan alınması.", "İcra yoluyla zorla da yapılabilir.", "İcra"],
  ["MENKUL", "Bir yerden başka yere taşınabilen mal.", "Taşınmazın karşıtıdır.", "Eşya"],
  ["AKİT", "İki tarafın karşılıklı ve uygun iradeleriyle kurulan hukuki işlem.", "Sözleşme ile aynı anlama gelir.", "Borçlar"],
  ["SİCİL", "Hukuki durumların kaydedildiği ve kamuya açık resmî kayıt.", "Ticaret ve tapu için ayrı ayrı tutulur.", "Genel"],
  ["ZİNA", "Evli bir kişinin eşi dışındaki biriyle cinsel ilişkiye girmesi.", "Boşanma sebeplerinden biridir.", "Aile"],
  ["KOLLUK", "Suçu önleyen ve soruşturmada savcılığa yardım eden güvenlik birimleri.", "Polis ve jandarma bu kapsamdadır.", "Ceza"],
  ["MÜDAFAA", "Bir saldırıya veya iddiaya karşı kendini koruma.", "Meşru olanı cezayı kaldırır.", "Ceza"],
  ["KATİP", "Mahkemede tutanakları yazan ve dosyaları düzenleyen görevli.", "Duruşmada hâkimin söylediklerini yazar.", "Usul"],
  ["ŞAHSİYET", "Hak ve borçlara sahip olabilme niteliği; kişilik.", "Bu hakların ihlali manevi tazminat doğurur.", "Medeni"],
  ["İMTİYAZ", "Bir kişiye veya gruba tanınan özel hak ve ayrıcalık.", "Anayasa kişilere böyle bir ayrıcalık tanınmasını yasaklar.", "Anayasa"],
  ["İTHAM", "Bir kişiyi suç işlemekle suçlama.", "İddianamede kişiye yöneltilir.", "Ceza"],
  ["TÜZÜK", "Kanunun uygulamasını göstermek için çıkarılan düzenleyici işlem.", "Dernekler de kendi kurallarını böyle bir metinle yazar.", "İdare"],
  ["FUHUŞ", "Para karşılığı cinsel ilişki.", "Buna aracılık etmek suçtur.", "Ceza"],
  ["BEYANNAME", "Bir bilginin resmî makama bildirildiği yazılı belge.", "Gelir vergisi için her yıl verilir.", "Vergi"],
  ["ERTELEME", "Bir işlemin veya cezanın infazının ileri bir tarihe bırakılması.", "Kısa hapis cezaları bu şekilde infaz edilmeyebilir.", "Ceza"],
  ["TASDİK", "Bir belgenin veya işlemin yetkili makamca onaylanması.", "Noter fotokopiye bu işlemi yapar.", "Genel"],
  ["RÜŞT", "Kişinin hukuki işlem yapabilecek yaşa ve olgunluğa ulaşması; erginlik.", "On beş yaşındaki kişiye mahkemece de verilebilir.", "Medeni"],
  ["HİBE", "Bir malın karşılıksız olarak başkasına verilmesi.", "Bağışlama sözleşmesi ile yapılır.", "Borçlar"],
  ["MUAFİYET", "Bir yükümlülükten kanunen bağışık tutulma.", "Vergiden bu şekilde kurtulunabilir.", "Vergi"],
  ["MEVZUAT", "Yürürlükteki hukuk kurallarının bütünü.", "Kanun, yönetmelik ve tüzükleri kapsar.", "Genel"],
  ["ZABITA", "Belediye kurallarına uyulmasını denetleyen görevliler.", "Seyyar satıcıları denetler.", "İdare"],
  ["TAAHHÜT", "Bir şeyi yapmayı veya vermeyi hukuken bağlayıcı biçimde üstlenme.", "Abonelik sözleşmelerinde süreli olarak verilir.", "Borçlar"],
  ["KAYYUM", "Bir malvarlığını veya işi yönetmek için mahkemece atanan kişi.", "Şirket veya dernek yönetimine de atanabilir.", "Medeni"],
  ["İLTİCA", "Zulüm korkusuyla başka bir ülkeye sığınma.", "Mülteci statüsü bu talep üzerine verilir.", "Anayasa"],
  ["MÜTEAHHİT", "Bir yapıyı yapmayı üstlenen kişi veya şirket.", "Kat karşılığı inşaatı o yapar.", "Borçlar"],
  ["MUTABAKAT", "Tarafların bir konuda anlaşmaya varması ve bunu belgelemesi.", "Şirketler hesaplarını bu belgeyle karşılaştırır.", "Ticaret"],
  ["VETO", "Bir kararın yürürlüğe girmesini önleme yetkisi.", "BM Güvenlik Konseyinde beş ülkenin bu hakkı vardır.", "Anayasa"],
  ["EMSAL", "Benzer bir olayda daha önce verilmiş ve örnek alınan karar.", "Yargıtay kararları bu şekilde gösterilir.", "Usul"],
  ["İNTİKAL", "Bir hakkın veya malın kanun gereği başkasına geçmesi.", "Mirasta mallar mirasçılara bu şekilde geçer.", "Miras"],
  ["CEBİR", "Bir kişiye karşı fiziksel güç kullanma.", "İradeyi bozan zorlamalardandır.", "Ceza"],
  ["SAYIŞTAY", "Kamu harcamalarını Meclis adına denetleyen yüksek mahkeme.", "Bakanlıkların hesaplarını inceler.", "İdare"],
  ["UYUŞMAZLIK", "Taraflar arasında hukuki bir konuda çıkan anlaşmazlık.", "Mahkeme bunu çözmek için vardır.", "Usul"],
  ["MERA", "Köylülerin hayvanlarını otlatmasına ayrılmış kamu arazisi.", "Özel mülkiyete konu olamaz.", "Eşya"],
  ["BONO", "Düzenleyenin belirli bir parayı belirli tarihte ödeyeceğini bildiren kıymetli evrak.", "Halk arasında senet denir.", "Ticaret"],
  ["POLİÇE", "Düzenleyenin bir başkasına belirli parayı ödemesini emrettiği kıymetli evrak; sigorta belgesi.", "Sigorta sözleşmesinin belgesine de bu ad verilir.", "Ticaret"],
  ["TACİR", "Bir ticari işletmeyi kısmen de olsa kendi adına işleten kişi.", "Basiretli davranmakla yükümlüdür.", "Ticaret"],
  ["CİRO", "Kıymetli evrakın arkasına imza atılarak başkasına devredilmesi.", "Çek bu yolla elden ele geçer.", "Ticaret"],
  ["TUTANAK", "Bir olayın veya toplantının resmî olarak yazıya geçirildiği belge.", "Kazadan sonra taraflar birlikte doldurur.", "Usul"],
  ["MÜVEKKİL", "Kendisini bir avukat veya vekille temsil ettiren kişi.", "Avukat onun adına dava açar.", "Usul"],
  ["MUHAKEME", "Mahkemenin bir uyuşmazlığı inceleyip karara bağlaması; yargılama.", "Hukuk ve ceza için ayrı kanunlar vardır.", "Usul"],
  ["VERASET", "Mirasçı olma durumu.", "Bu belge mirasçıları ve paylarını gösterir.", "Miras"],
  ["MURİS", "Ölümüyle mirası açılan kişi; miras bırakan.", "Terekenin önceki sahibidir.", "Miras"],
  ["MÜZAYEDE", "Malın en yüksek fiyatı verene satıldığı açık artırma.", "Antika ve sanat eserleri bu yolla satılır.", "Ticaret"],
  ["ZİMMET", "Kamu görevlisinin görevi gereği elindeki malı kendine mal etmesi.", "Memurun işlediği ağır suçlardandır.", "Ceza"],
  ["MÜKELLEF", "Vergi ödemekle yükümlü olan kişi.", "Vergi dairesinde numarasıyla kayıtlıdır.", "Vergi"],
  ["MUHTIRA", "Bir konuda resmî uyarı niteliğinde yazılı bildiri.", "Askerin hükümete verdiği uyarılar da bu adla anılır.", "Anayasa"],
  ["İNTİHAL", "Başkasının eserini kaynak göstermeden kendisininmiş gibi kullanma.", "Akademide bu aşırma yazılımlarla tespit edilir.", "Ticaret"],
  ["İHTAR", "Bir yükümlülüğün yerine getirilmesi için yapılan resmî uyarı.", "Noter aracılığıyla da yapılabilir.", "Borçlar"],
  ["VASİ", "Küçük veya kısıtlı kişiyi korumak için mahkemece atanan kişi.", "Velayet altında olmayanların işlerini yürütür.", "Medeni"],
  ["DEPOZİTO", "Bir sözleşmeden doğabilecek zarara karşı peşin verilen güvence parası.", "Ev kiralarken ev sahibine verilir.", "Borçlar"],
  ["MOBBİNG", "İş yerinde bir çalışanın sistematik olarak yıldırılması.", "Psikolojik taciz olarak da bilinir.", "İş"],
  ["LOKAVT", "İşverenin işçileri topluca işten uzaklaştırması.", "Grevin işveren tarafındaki karşılığıdır.", "İş"],
  ["ŞARTNAME", "Bir ihale veya işin koşullarını gösteren belge.", "İhaleye girenler bu belgeyi satın alır.", "İdare"],
  ["İLMÜHABER", "Kişinin bir durumunu gösteren resmî belge.", "Muhtardan alınan ikamet belgesi bunun örneğidir.", "İdare"],
  ["PAFTA", "Kadastrosu yapılmış yerlerin ada ve parsellerini gösteren harita.", "Tapuda taşınmazın yeri bununla bulunur.", "Eşya"],
  ["MUKAVELE", "İki tarafın karşılıklı yükümlülük altına girdiği anlaşma; sözleşme.", "Eski metinlerde akit yerine kullanılır.", "Borçlar"],
  ["ONAMA", "Üst mahkemenin alt mahkeme kararını uygun bulması.", "Bozmanın karşıtıdır.", "Usul"],
  ["İKAMETGAH", "Kişinin sürekli kalma niyetiyle oturduğu yer.", "Davalar çoğunlukla bu yerin mahkemesinde açılır.", "Medeni"],
  ["AZİL", "Verilen vekâlet veya görev yetkisinin geri alınması.", "Müvekkil avukatını bu yolla görevden alır.", "Borçlar"],
  ["MAZBATA", "Bir kurulun kararını veya seçim sonucunu gösteren resmî belge.", "Seçimi kazanan milletvekiline verilir.", "İdare"],
  ["ACENTA", "Bir tacir adına sürekli olarak sözleşme yapan veya buna aracılık eden kişi.", "Sigorta ve turizmde sık görülür.", "Ticaret"],
  ["MÜBAŞİR", "Mahkemede tarafları ve tanıkları duruşmaya çağıran görevli.", "Koridorda isimleri yüksek sesle o okur.", "Usul"],
  ["MAKTUL", "Kasten öldürülen kişi.", "Öldürme suçlarında mağdurun adıdır.", "Ceza"],
  ["GENSORU", "Meclisin hükümeti veya bir bakanı denetlemek için açtığı görüşme.", "Sonunda güvensizlik oylaması yapılabilir.", "Anayasa"],
  ["PARAF", "Adın baş harfleriyle atılan kısa imza.", "Sözleşmenin her sayfasına atılır.", "Genel"],
  ["DOKTRİN", "Hukuk bilim insanlarının görüşlerinin bütünü; öğreti.", "Mahkemeler kararlarında bu görüşlere de başvurur.", "Genel"],
  ["OMBUDSMAN", "İdarenin işlemlerine karşı vatandaş şikâyetlerini inceleyen kamu denetçisi.", "Türkiye'de Kamu Denetçiliği Kurumu bu görevi yürütür.", "İdare"],
  ["DEVREMÜLK", "Bir taşınmazdan yılın belirli dönemlerinde sırayla yararlanma hakkı.", "Tatil evlerinde yaygındır.", "Eşya"],
];
