import type { WordRow } from "./campaignWords";

// New campaign terms (hard). Same row shape as easyRows.
export const hardRows: readonly WordRow[] = [
  ["İRAT", "Bir maldan veya haktan düzenli olarak elde edilen gelir.", "Kira geliri bunun tipik örneğidir.", "Borçlar"],
  ["YOKLUK", "Kurucu unsuru eksik olduğu için hukuken hiç doğmamış sayılan işlemin durumu.", "Butlandan bile ağır bir sakatlıktır.", "Genel"],
  ["EDA", "Borçlunun yerine getirmesi gereken şey; borcun konusu.", "Bu davada mahkemeden bir şeyin verilmesine veya yapılmasına hükmedilmesi istenir.", "Borçlar"],
  ["TEFSİR", "Bir hukuk kuralının anlamının ve kapsamının belirlenmesi; yorum.", "Lafzi ve amaçsal olarak yapılabilir.", "Genel"],
  ["ACİZ", "Borçlunun borcunu ödeyemeyecek durumda olması.", "İcrada bu durumu gösteren belgeye vesika denir.", "İcra"],
  ["MÜTEVELLİ", "Bir vakfın yönetimiyle görevlendirilen kişi veya kurul.", "Vakıf üniversitelerinde bu heyet bulunur.", "Medeni"],
  ["DEFİ", "Davalının, hakkı ortadan kaldırmadan ifadan kaçınmasını sağlayan savunma aracı.", "Zamanaşımı bu türden bir savunmadır.", "Usul"],
  ["HASILAT", "Bir işten veya maldan elde edilen gelir ve ürün.", "Bu tür kirada kira bedeli ürünle ödenir.", "Borçlar"],
  ["MÜDAHİL", "Görülmekte olan bir davaya sonradan katılan üçüncü kişi.", "Taraflardan birinin yanında yer alabilir.", "Usul"],
  ["SAHİH", "Hukuka uygun olarak kurulmuş, geçerli.", "Batılın karşıtıdır.", "Genel"],
  ["TAHRİR", "Bir şeyin yazıya geçirilmesi; resmî kayıt yazımı.", "Eski nüfus sayımları bu adla anılır.", "İdare"],
  ["REPLİK", "Davacının, davalının cevap dilekçesine karşı verdiği dilekçe.", "Buna karşı davalı düplik verir.", "Usul"],
  ["MECRA", "Suyun aktığı yol; bir taşınmazdan geçen boru veya kablo hattı.", "Komşu taşınmazdan geçirme hakkı kanunla tanınır.", "Eşya"],
  ["HALEF", "Bir kişinin hak ve borçlarını devralan, onun yerine geçen kişi.", "Selefin karşıtıdır.", "Medeni"],
  ["ZAYİ", "Kaybolmuş, yitik.", "Bu durumdaki çek için mahkemeden iptal kararı alınır.", "Ticaret"],
  ["İCAZET", "Yetkisiz yapılmış bir işleme sonradan verilen onay.", "Vekâletsiz iş görmede sonradan verilebilir.", "Borçlar"],
  ["FUZULİ", "Hakkı olmadan başkasının malını kullanan veya işini gören.", "Bu şekilde kullanılan taşınmaz için ecrimisil istenir.", "Eşya"],
  ["TAHKİKAT", "Bir olayın aydınlatılması için yapılan araştırma ve soruşturma.", "Hukuk davasında delillerin toplandığı evredir.", "Usul"],
  ["MECUR", "Kiraya verilen şey.", "Kira sözleşmesinin konusudur.", "Borçlar"],
  ["İSNAT", "Bir suçu veya eylemi bir kişiye yükleme.", "Haksız yapılırsa iftira olur.", "Ceza"],
  ["AVAL", "Kambiyo senedinin ödenmesini güvence altına alan kefalet.", "Senedin önüne 'için' yazılarak imza atılır.", "Ticaret"],
  ["HUSUMET", "Davada taraf olma sıfatı; düşmanlık.", "Davalının yanlış gösterilmesi bu sıfat yokluğu sayılır.", "Usul"],
  ["FEZLEKE", "Bir soruşturmanın özetlendiği ve sonucunun bildirildiği yazı.", "Milletvekilinin dokunulmazlığı için Meclise gönderilir.", "Ceza"],
  ["HASIM", "Davada karşı taraf.", "Husumet kelimesiyle aynı köktendir.", "Usul"],
  ["İSTİMLAK", "Kamu yararı için özel mülkün bedeli ödenerek devletçe alınması.", "Kamulaştırma ile aynı anlama gelir.", "İdare"],
  ["İBRAZ", "Bir belgenin yetkili makama veya borçluya gösterilmesi.", "Çek bankaya bu şekilde sunulur.", "Ticaret"],
  ["İKTİSAP", "Bir hakkın veya malın edinilmesi.", "Mülkiyet zilyetlikle de edinilebilir.", "Eşya"],
  ["DONATAN", "Gemisini deniz ticaretinde kullanan gemi sahibi.", "Deniz ticareti hukukunun temel kişisidir.", "Ticaret"],
  ["TESELSÜL", "Birden çok borçlunun aynı borcun tamamından sorumlu olması.", "Alacaklı borcun tamamını dilediğinden isteyebilir.", "Borçlar"],
  ["NAVLUN", "Deniz yoluyla eşya taşımada ödenen taşıma ücreti.", "Konşimentoda gösterilir.", "Ticaret"],
  ["RESEN", "Bir talep olmaksızın kendiliğinden.", "Hâkim bazı hususları bu şekilde dikkate alır.", "Usul"],
  ["ZIYA", "Bir şeyin kaybolması veya elden çıkması.", "Vergi ödenmeyince bu ad verilen ceza kesilir.", "Vergi"],
  ["ZİLYET", "Bir şey üzerinde fiilî hâkimiyeti bulunan kişi.", "Malik olmak zorunda değildir.", "Eşya"],
  ["MUACCEL", "Vadesi gelmiş, ödenmesi istenebilir.", "Bu duruma gelen borç için ihtar çekilebilir.", "Borçlar"],
  ["TAHAKKUK", "Bir verginin veya alacağın miktarının kesinleşmesi.", "Tarhtan sonra gelen aşamadır.", "Vergi"],
  ["TARH", "Vergi alacağının vergi dairesince hesaplanarak belirlenmesi.", "Vergilendirme sürecinin ilk aşamasıdır.", "Vergi"],
  ["MÜFLİS", "Hakkında iflas kararı verilmiş kişi.", "Malları iflas masasına girer.", "İcra"],
  ["MAHSUP", "Bir alacağın başka bir borçtan düşülerek hesaplanması.", "Ödenen avans maaştan bu şekilde düşülür.", "Borçlar"],
  ["RİZİKO", "Sigortanın güvence altına aldığı tehlike.", "Gerçekleşirse tazminat ödenir.", "Ticaret"],
  ["LEHTAR", "Kıymetli evrakta ödemenin kendisine yapılacağı kişi.", "Bonoda adı yazılı alacaklıdır.", "Ticaret"],
  ["MUVAFAKAT", "Bir işleme rıza gösterme, onay verme.", "Velinin bu şekilde onayı gerekebilir.", "Genel"],
  ["İSTİHKAK", "Bir malın üçüncü kişiye ait olduğunu ileri sürme hakkı.", "Haczedilen malın başkasına ait olduğu iddiasıyla dava açılır.", "İcra"],
  ["VAKIA", "Hukuki sonuç doğuran olay veya olgu.", "Mahkemede taraflarca ileri sürülür ve ispatlanır.", "Usul"],
  ["MATRAH", "Vergi miktarının hesaplanmasında esas alınan değer.", "Vergi oranı bu değere uygulanır.", "Vergi"],
  ["MÜTESELSİL", "Her biri borcun tamamından sorumlu olan; zincirleme.", "Kefaletin ağır türü bu niteliktedir.", "Borçlar"],
  ["RAYİÇ", "Bir malın piyasada geçerli olan değeri.", "Emlak vergisinde bu bedel esas alınır.", "Vergi"],
  ["İTFA", "Bir borcun ödenerek sona erdirilmesi.", "Tahvil borçları bu şekilde kapatılır.", "Borçlar"],
  ["NİSAP", "Bir kurulun toplanabilmesi veya karar alabilmesi için gereken en az sayı.", "Mecliste karar yeter sayısı bunun örneğidir.", "Anayasa"],
  ["KAMBİYO", "Poliçe, bono ve çek gibi kanunda düzenlenen kıymetli evraka özgü kurallar.", "Bu senetlere dayalı icra takibi daha hızlıdır.", "Ticaret"],
  ["MÜCBİR", "Önlenemeyen ve kaçınılmaz olan; zorlayıcı.", "Deprem ve sel bu tür sebeplerdendir.", "Borçlar"],
  ["CİRANTA", "Bir kıymetli evrakı ciro ederek devreden kişi.", "Senet ödenmezse o da sorumlu olur.", "Ticaret"],
  ["İSTİNABE", "Başka yerdeki bir işlemin oradaki mahkemeden istenmesi.", "Uzaktaki tanık bu yolla dinlenir.", "Usul"],
  ["RÜÇHAN", "Öncelik ve üstünlük hakkı.", "Ortaklara yeni payları önce alma hakkı tanınır.", "Ticaret"],
  ["TEAMÜL", "Toplumda süregelen ve uyulan uygulama; örf.", "Ticarette yerleşik olanı hukuk kuralı sayılabilir.", "Genel"],
  ["TEFHİM", "Kararın duruşmada taraflara sözlü olarak bildirilmesi.", "Kısa karar bu şekilde açıklanır.", "Usul"],
  ["MÜMESSİL", "Bir kişi veya kurum adına hareket eden; temsilci.", "Ticari olanı işletmeyi yönetir.", "Ticaret"],
  ["İSTİCVAP", "Tarafın, bilgi sahibi olduğu olay hakkında mahkemece sorguya çekilmesi.", "Hukuk davasında karşı tarafa bu yolla soru sorulur.", "Usul"],
  ["TEVSİK", "Bir hususun belgeyle kanıtlanması.", "Vergi giderleri faturayla bu şekilde kanıtlanır.", "Vergi"],
  ["İFRAZ", "Bir parselin birden fazla parçaya ayrılması.", "Tevhidin karşıtıdır.", "Eşya"],
  ["İMTİNA", "Bir şeyi yapmaktan kaçınma.", "Tanıklıktan bu şekilde çekinilebilir.", "Usul"],
  ["GAİP", "Ölüm tehlikesi içinde kaybolan veya uzun süredir haber alınamayan kişi.", "Mahkeme bu kişi hakkında karar verebilir.", "Medeni"],
  ["HISIM", "Kan bağı veya evlilik yoluyla akraba olan kişi.", "Kayın ve kan türleri vardır.", "Aile"],
  ["MAHCUZ", "Üzerine haciz konulmuş.", "Bu mal satılamaz ve devredilemez.", "İcra"],
  ["TEVKİL", "Vekilin yetkisini başka birine devretmesi.", "Avukat bu yetki varsa başka avukata devredebilir.", "Borçlar"],
  ["MAKTU", "Önceden belirlenmiş, sabit tutarlı.", "Harçların bir kısmı bu şekilde, sabit alınır.", "Vergi"],
  ["TALİK", "Bir işlemin hükmünün bir şarta veya zamana bağlanması.", "Şarta bağlı işlem bu şekilde ertelenir.", "Borçlar"],
  ["TEDAVÜL", "Paranın veya kıymetli evrakın elden ele dolaşması.", "Banknotlar bu şekilde piyasada dolaşır.", "Ticaret"],
  ["MÜTALAA", "Savcının veya bilirkişinin bir konudaki görüşü.", "Ceza davasında savcı esas hakkında bunu sunar.", "Ceza"],
  ["YEDİEMİN", "Uyuşmazlık konusu malın saklanması kendisine bırakılan güvenilir kişi.", "Çekilen araçlar bu otoparklarda tutulur.", "İcra"],
  ["TADİL", "Bir metin veya işlemde değişiklik yapma.", "Kanunlar bu yolla güncellenir.", "Genel"],
  ["TRAMPA", "Bir malın başka bir malla değiştirilmesi.", "Parasız yapılan değişim sözleşmesidir.", "Borçlar"],
  ["İVAZ", "Bir edimin karşılığı olan bedel.", "Bağışlama bu karşılık olmadan yapılır.", "Borçlar"],
  ["TAVZİH", "Belirsiz bir mahkeme kararının açıklanması.", "Tarafların talebiyle hükmü değiştirmeden yapılır.", "Usul"],
  ["İSTİRDAT", "Haksız yere ödenen veya alınan şeyin geri istenmesi.", "Borç olmadığı hâlde ödenen para için bu dava açılır.", "İcra"],
  ["MÜKERRİR", "Önceki cezası kesinleştikten sonra yeniden suç işleyen kişi.", "Tekerrür hükümleri ona uygulanır.", "Ceza"],
  ["DERDEST", "Henüz görülmekte olan, sonuçlanmamış.", "Aynı konuda böyle bir dava varken yenisi açılamaz.", "Usul"],
  ["MÜELLİF", "Bir eseri meydana getiren kişi; eser sahibi.", "Fikri hakların sahibidir.", "Ticaret"],
  ["İLGA", "Bir kuralın yeni bir düzenlemeyle yürürlükten kaldırılması.", "Kaldırılan kanun maddesi mülga olur.", "Genel"],
  ["EMARE", "Tek başına kanıt sayılmayan ama bir olgunun varlığına işaret eden durum.", "Delil başlangıcı olarak değerlendirilebilir.", "Usul"],
  ["İRTİKAP", "Kamu görevlisinin görevini kötüye kullanarak haksız çıkar sağlaması.", "Rüşvete yakın bir memur suçudur.", "Ceza"],
  ["TEBELLÜĞ", "Tebliğ edilen bir belgenin alınması.", "Belgeyi alan kişi imzasıyla bunu gösterir.", "Usul"],
  ["MUHAMMEN", "Tahmin edilen.", "İhalede başlangıç için bu bedel belirlenir.", "İdare"],
  ["HALEFİYET", "Bir kişinin başkasının hukuki durumuna onun yerine geçerek girmesi.", "Borcu ödeyen kefil alacaklının yerine bu şekilde geçer.", "Borçlar"],
  ["CELSE", "Mahkemenin bir davayı görmek için yaptığı her bir oturum.", "Bir dava birçok oturumda görülebilir.", "Usul"],
  ["TAHKİK", "Bir hususun gerçeğe uygun olup olmadığının araştırılması.", "Mahkeme delilleri bu şekilde inceler.", "Usul"],
  ["MEHİL", "Bir işin yapılması için tanınan süre.", "Hâkim ödeme için kısa bir süre verebilir.", "Usul"],
  ["SİMSARLIK", "Sözleşme yapılmasına aracılık edip ücret alma.", "Tellallık da denir; emlakçılık buna örnektir.", "Ticaret"],
  ["ÖNEL", "Bir işin yapılması için verilen süre.", "Mehil sözcüğünün öz Türkçe karşılığıdır.", "Usul"],
  ["TEHİR", "Bir işlemin ileri bir zamana bırakılması.", "Kanun yoluna başvurunca icranın geri bırakılması istenebilir.", "İcra"],
  ["MERHUN", "Rehin olarak verilmiş mal.", "Borç ödenmezse satılır.", "Eşya"],
  ["MÜEYYİDE", "Bir hukuk kuralına uyulmamasının sonucu olan yaptırım.", "Ceza, tazminat ve iptal bunun türleridir.", "Genel"],
  ["MÜTEMERRİT", "Borcunu vadesinde ödemeyip temerrüde düşen.", "Bu borçlu gecikme faizi öder.", "Borçlar"],
  ["İNFİSAH", "Bir sözleşmenin kendiliğinden sona ermesi.", "İfa imkânsızlaşınca sözleşme bu şekilde ortadan kalkar.", "Borçlar"],
  ["İMHAL", "Borçluya ödeme için süre verilmesi.", "Mahkeme hakkaniyete göre tanıyabilir.", "Borçlar"],
  ["İZALE", "Bir durumun giderilmesi, ortadan kaldırılması.", "Ortaklığın giderilmesi davasının eski adı bununla kurulur.", "Eşya"],
  ["TASHİH", "Bir kayıttaki yanlışlığın düzeltilmesi.", "Nüfus kaydındaki yaş bu davayla düzeltilir.", "Medeni"],
  ["TEDİYE", "Bir borcun ödenmesi.", "Makbuz bu işlemi gösterir.", "Borçlar"],
  ["VARAKA", "Belge, yazılı kâğıt.", "Seçimlerde oy pusulası bu adla anılır.", "Genel"],
  ["İHTARNAME", "Karşı tarafa noter aracılığıyla gönderilen resmî uyarı yazısı.", "Temerrüde düşürmek için çekilir.", "Borçlar"],
  ["SAİK", "Bir kişiyi bir eylemi yapmaya yönelten sebep.", "Ceza hukukunda bazen ağırlaştırıcı sayılır.", "Ceza"],
  ["TECİL", "Bir işin ileri bir tarihe ertelenmesi.", "Askerlik ve vergi borcu ertelenebilir.", "İdare"],
  ["TEVKİF", "Bir kişinin tutuklanması; bir şeyin alıkonulması.", "Vergide kaynakta kesinti de bu adla anılır.", "Ceza"],
  ["FERAĞ", "Bir taşınmazın mülkiyetinin tapuda devredilmesi.", "Tapuda satış bu işlemle tamamlanır.", "Eşya"],
  ["İCBAR", "Bir kişiyi bir şeyi yapmaya zorlama.", "Ortaklığın kanunen zorunlu kılınması da bu adla anılır.", "Genel"],
  ["TENFİZ", "Yabancı mahkeme kararının Türkiye'de uygulanabilir hâle getirilmesi.", "Tanımadan farklı olarak icra kabiliyeti kazandırır.", "Usul"],
  ["TAHKİR", "Bir kişiyi aşağılama, onurunu kırma.", "Hakaret suçunun eski adıdır.", "Ceza"],
  ["TAKYİT", "Bir hakkın sınırlandırılması.", "Tapudaki haciz ve ipotek kayıtları bu türdendir.", "Eşya"],
  ["MAZNUN", "Hakkında dava açılmış kişi; sanık.", "Eski ceza usul kanununda kullanılan addır.", "Ceza"],
  ["ŞİFAHİ", "Sözlü olarak yapılan.", "Yazılının karşıtıdır.", "Genel"],
  ["İSTİNKAF", "Bir işi yapmaktan kaçınma.", "Hâkimin karar vermekten kaçınması suçtur.", "Usul"],
  ["ECRİMİSİL", "Bir taşınmazı haksız kullanan kişiden istenen kullanım bedeli.", "Fuzuli işgal edenden istenir.", "Eşya"],
  ["MÜZEKKERE", "Mahkemenin başka bir makama yazdığı resmî yazı.", "Kayıtlar bu yazıyla istenir.", "Usul"],
  ["NEMA", "Bir paranın veya malın getirdiği gelir.", "Mevduat faizi bunun örneğidir.", "Borçlar"],
  ["İSKAT", "Bir hakkın düşürülmesi veya kaldırılması.", "Hak sahibi kendi isteğiyle de vazgeçebilir.", "Genel"],
  ["CÜRÜM", "Suç; eski hukukta kabahatten ağır suç türü.", "Suçüstüne eskiden meşhut olanı denirdi.", "Ceza"],
  ["TEVZİ", "Dağıtma, paylaştırma.", "Davalar mahkemelere bu yolla dağıtılır.", "Usul"],
  ["TEMETTÜ", "Şirketin ortaklarına dağıttığı kâr payı.", "Hissedarlar her yıl bunu bekler.", "Ticaret"],
  ["TECZİYE", "Cezalandırma.", "Cezai bir yaptırım uygulamayı anlatır.", "Ceza"],
  ["ALENİYET", "Açıklık; herkesin görebileceği ve duyabileceği biçimde yapılma.", "Duruşmalar kural olarak bu ilkeyle yapılır.", "Usul"],
  ["MÜKTESEP", "Kazanılmış, edinilmiş.", "Bu tür hak sonradan geri alınamaz.", "İdare"],
  ["İCAR", "Kiraya verme.", "Kira sözleşmesinin eski adıdır.", "Borçlar"],
  ["NESEP", "Çocuk ile anne veya babası arasındaki soy bağı.", "Soybağının eski adıdır.", "Aile"],
  ["SÜKNA", "Bir binada oturma hakkı.", "Kişiye bağlı bir irtifak hakkıdır.", "Eşya"],
  ["ANTREPO", "Gümrüğe gelen eşyanın vergisi ödenmeden konulduğu depo.", "Gümrük işlemleri bitene kadar eşya burada bekler.", "Ticaret"],
  ["CELPNAME", "Bir kişiyi mahkemeye çağırmak için gönderilen resmî yazı.", "Tanıklara bu yazıyla duruşma günü bildirilir.", "Usul"],
  ["MÜRTEHİN", "Rehin hakkına sahip alacaklı.", "Rehni veren kişinin karşı tarafıdır.", "Eşya"],
  ["SUİNİYET", "Kötü niyet.", "İyiniyetin karşıtıdır.", "Medeni"],
  ["GASIB", "Başkasının malını zorla ve haksız yere alan kişi.", "Gasp eden kişiye denir.", "Ceza"],
  ["İKRAZ", "Ödünç para verme.", "Bankaların kredi vermesi bu işleme dayanır.", "Borçlar"],
  ["VEDİA", "Saklanmak üzere birine bırakılan mal; emanet.", "Saklama sözleşmesinin konusudur.", "Borçlar"],
  ["BAĞIT", "İki tarafın anlaşmasıyla kurulan işlem; sözleşme.", "Akdin öz Türkçe karşılığıdır.", "Borçlar"],
  ["KEŞİDE", "Bir çekin veya poliçenin düzenlenip imzalanması.", "Bu tarihi çek üzerinde yazılıdır.", "Ticaret"],
  ["DESİSE", "Aldatmak için yapılan hile, oyun.", "Dolandırıcılık suçunun aracıdır.", "Ceza"],
  ["MÜDDEİ", "Davacı; iddiada bulunan.", "Savcının eski adı bu kelimeyle kurulur.", "Usul"],
  ["İLTİMAS", "Birini kayırmak için aracılık etme; torpil.", "Kamu hizmetinde eşitlik ilkesine aykırıdır.", "İdare"],
  ["ARZUHAL", "Bir makama sunulan yazılı istek; dilekçe.", "Eskiden bunları adliye önünde yazan kişiler vardı.", "Usul"],
  ["İBRANAME", "Alacaklının borçluyu borçtan kurtardığını gösteren belge.", "İşçi ayrılırken işverene imzalar.", "İş"],
  ["GAYBUBET", "Bir kişinin ortada olmaması, kayıp olması.", "Ceza davasında sanığın yokluğunda yapılan yargılamayı anlatır.", "Ceza"],
  ["EHLİVUKUF", "Uzmanlık gerektiren konuda görüşüne başvurulan kişi; bilirkişi.", "Eski hukuk dilinde kullanılırdı.", "Usul"],
  ["MÜŞTEMİLAT", "Bir binanın eklentileri.", "Garaj, kömürlük ve depo bunun örnekleridir.", "Eşya"],
  ["KABZ", "Bir şeyi teslim alıp eline geçirme.", "Bu şekilde teslim alma bazı işlemlerde geçerlilik şartıdır.", "Borçlar"],
  ["ŞUFA", "Paydaşın, satılan payı öncelikle satın alma hakkı; önalım.", "Paydaş, payın üçüncü kişiye satışında bu hakkı kullanır.", "Eşya"],
  ["HACİR", "Bir kişinin fiil ehliyetinin mahkeme kararıyla kısıtlanması.", "Kısıtlılığın eski adıdır.", "Medeni"],
  ["İKALE", "Tarafların anlaşarak bir sözleşmeyi sona erdirmesi.", "İş sözleşmesi bu yolla karşılıklı bitirilebilir.", "Borçlar"],
  ["İTLAF", "Bir şeyi yok etme, telef etme.", "Başkasının malını bu şekilde bozmak tazminat doğurur.", "Ceza"],
  ["SEMEN", "Satış sözleşmesinde alıcının ödediği bedel.", "Satılan malın karşılığıdır.", "Borçlar"],
  ["LAYİHA", "Mahkemeye verilen yazılı dilekçe; tasarı.", "Cevap dilekçesi de bu adla anılır.", "Usul"],
  ["TERHİN", "Bir malı rehin olarak verme.", "Borç için güvence gösterme yoludur.", "Eşya"],
  ["ARİYET", "Bir malın karşılıksız olarak kullanılmak üzere ödünç verilmesi.", "Kullanım ödüncü sözleşmesinin eski adıdır.", "Borçlar"],
  ["TÖHMET", "Bir kişiye yüklenen suç; suçlama.", "Henüz aydınlanmamış suç şüphesini anlatır.", "Ceza"],
  ["VAKFİYE", "Vakfın amacını ve kurallarını gösteren kuruluş belgesi.", "Vakıf senedi olarak da bilinir.", "Medeni"],
  ["MAMELEK", "Bir kişinin sahip olduğu malların bütünü; malvarlığı.", "Aktif ve pasifleri kapsar.", "Medeni"],
  ["TAAMMÜT", "Bir suçu önceden tasarlayarak işleme.", "Kasten öldürmede ağırlaştırıcı sebeptir.", "Ceza"],
  ["TEBERRU", "Bir şeyi karşılıksız olarak verme; bağış.", "Hayır kurumlarına yapılır.", "Borçlar"],
  ["KEŞİDECİ", "Çeki veya poliçeyi düzenleyip imzalayan kişi.", "Çekin karşılıksız çıkmasından o sorumludur.", "Ticaret"],
  ["MÜSTECİR", "Bir şeyi kiralayan kişi; kiracı.", "Kiraya verenin karşı tarafıdır.", "Borçlar"],
  ["PLEBİSİT", "Bir konunun halkın oyuna sunulması; halk oylaması.", "Toprak ve egemenlik sorunlarında başvurulur.", "Anayasa"],
  ["MALPRAKTİS", "Hekimin hatalı tıbbi uygulamayla hastaya zarar vermesi.", "Tazminat davalarına konu olur.", "Borçlar"],
  ["TEMLİKNAME", "Bir alacağın başkasına devredildiğini gösteren belge.", "Alacağın devri yazılı yapılmalıdır.", "Borçlar"],
];
