// One everyday example per term, shown only under the term in the Kavramlar collection.
// The term (or its inflected form) is wrapped in *asterisks* and rendered bold.
export const exampleSentences: Record<string, string> = {
  FERAGAT: "Borcun ödenmesi üzerine davacı, davasından *feragat* etti.",
  "ZİLYETLİK": "Eşyayı kiralayan kişi, malik olmasa da eşya üzerinde *zilyetlik* kazanır.",
  "İBRA": "İşten ayrılan işçi, bütün alacaklarını aldığını belirten bir *ibraname* imzaladı.",
  "İKRAR": "Davalı, duruşmada borcu olduğunu *ikrar* edince mahkeme davayı kabul etti.",
  "TEMERRÜT": "Kira ödeme günü geçtiği hâlde kirayı ödemeyen kiracı, *temerrüde* düştü.",
  "TEMYİZ": "Bölge adliye mahkemesinin kararını hukuka aykırı bulan taraf, dosyayı *temyiz* için Yargıtay'a taşıdı.",
  "İSTİNAF": "İlk derece mahkemesinin kararını beğenmeyen taraf, kararı *istinaf* yoluyla bölge adliye mahkemesine taşıdı.",
  "TEBLİGAT": "Mahkemenin gönderdiği *tebligat*, adresinde bulunamayan davalı için mahalle muhtarına bırakıldı.",
  VEKALET: "Avukat, müvekkilinden aldığı *vekâletle* onun adına dava açtı.",
  "TAZMİNAT": "Kazada yaralanan yaya, kusurlu sürücüden maddi ve manevi *tazminat* istedi.",
  "VASİYET": "Yaşlı adam, kitaplarının ölümünden sonra kütüphaneye verilmesini *vasiyet* etti.",
  "TAHLİYE": "Kirasını ödemeyen kiracı hakkında mahkeme *tahliye* kararı verdi.",
  "İÇTİHAT": "Yargıtay'ın bu konudaki yerleşik *içtihadı*, ilk derece mahkemelerine yol gösterdi.",
  "İNTİFA": "Anne, evin mülkiyetini çocuklarına verdi ama ölünceye kadar evde oturabilmek için *intifa* hakkını kendine ayırdı.",
  "ZAMANAŞIMI": "Alacağını yıllarca istemeyen alacaklı, dava açtığında borçlunun *zamanaşımı* savunmasıyla karşılaştı.",
  "HACİZ": "Borcunu ödemeyen kişinin arabasına, alacaklının başlattığı icra takibinde *haciz* kondu.",
  "İPOTEK": "Ev almak için kredi çeken Aslı'nın evine banka lehine *ipotek* konuldu.",
  KEFALET: "Arkadaşının kredisi için *kefalet* sözleşmesi imzalayan Cem, borç ödenmeyince bankaya karşı sorumlu oldu.",
  NAFAKA: "Boşanmanın ardından mahkeme, çocuğun bakımı için babanın her ay *nafaka* ödemesine karar verdi.",
  VELAYET: "Boşanma davasında mahkeme, çocuğun *velayetini* anneye verdi.",
  VESAYET: "Anne ve babasını kaybeden küçük çocuk için mahkeme *vesayet* kararı vererek bir vasi atadı.",
  "MİRAS": "Dedesinden kalan *miras*, kanuni mirasçılar arasında paylaştırıldı.",
  "DELİL": "Davacı, iddiasını desteklemek için mesaj kayıtlarını *delil* olarak sundu.",
  TANIK: "Kazayı gören yaya, duruşmada *tanık* olarak dinlendi ve gördüklerini anlattı.",
  "BİLİRKİŞİ": "Mahkeme, kazadaki kusur oranlarının belirlenmesi için dosyayı *bilirkişiye* gönderdi.",
  BERAAT: "Delil yetersizliği nedeniyle sanık hakkında *beraat* kararı verildi.",
  KAST: "Sanığın olayı bilerek ve isteyerek yaptığı anlaşılınca mahkeme, *kastın* varlığını kabul etti.",
  "TAKSİR": "Dikkatsizce araç kullanıp bir yayaya çarpan sürücü, *taksirle* yaralama suçundan yargılandı.",
  "UZLAŞTIRMA": "Basit yaralama soruşturmasında savcılık, dosyayı *uzlaştırmaya* gönderdi.",
  DAVA: "Üst kattaki komşusunun su tesisatı yüzünden evi hasar gören Hasan, tazminat için *dava* açtı.",
  DAVACI: "*Davacı*, kira bedelinin tespiti için dava açtı ve dilekçesine kira sözleşmesini ekledi.",
  DAVALI: "Mahkeme, cevap dilekçesi vermesi için *davalıya* iki haftalık süre tanıdı.",
  "HÜKÜM": "Yargılamanın sonunda mahkeme, davacının haklı olduğuna dair *hüküm* kurdu.",
  "İLAM": "Davayı kazanan alacaklı, mahkeme *ilamıyla* icra dairesine başvurdu.",
  "DURUŞMA": "Mahkeme, tanıkların dinlenmesi için *duruşmayı* bir sonraki aya erteledi.",
  "DİLEKÇE": "Ali, sokak lambasının tamiri için belediyeye *dilekçe* verdi.",
  "YETKİ": "Ankara'da oturan davalıya karşı açılacak davada genel *yetkili* mahkeme, Ankara mahkemesidir.",
  "GÖREV": "İşçi ile işveren arasındaki ücret davasına bakma *görevi* iş mahkemesine aittir.",
  "İSPAT": "Borç verdiğini *ispat* edemeyen davacının davası reddedildi.",
  "KARİNE": "Kanuna göre evlilik içinde doğan çocuğun babası kocadır; bu bir *karinedir*.",
  "YEMİN": "Başka delili kalmayan davacı yemin teklif edince davalı, borcu olmadığına dair *yemin* etti.",
  "KEŞİF": "Sınır uyuşmazlığını çözmek için hâkim, bilirkişiyle birlikte tarlada *keşif* yaptı.",
  ISLAH: "Bilirkişi raporunda zararın daha yüksek çıkması üzerine davacı, *ıslah* ile talebini artırdı.",
  SULH: "Uzun süren davada taraflar, son duruşmada anlaşarak *sulh* oldu.",
  "TAHKİM": "İki şirket, sözleşmelerine anlaşmazlıkları *tahkim* yoluyla çözme şartı koydu.",
  HAKEM: "İki şirket, aralarındaki anlaşmazlığı mahkeme yerine bir *hakem* heyetinin çözmesini kararlaştırdı.",
  "İTİRAZ": "Haksız olduğunu düşündüğü ödeme emrine borçlu, yedi gün içinde *itiraz* etti.",
  "MÜLKİYET": "Tapuda adına kayıtlı evin *mülkiyeti* Zeynep'e aittir; evi satabilir veya kiraya verebilir.",
  "PAYDAŞ": "Tarlanın *paydaşlarından* biri, kendi payını diğerlerinin onayı olmadan satabilir.",
  "İRTİFAK": "Tarlasına ulaşmak için komşu araziden geçmesi gereken çiftçi lehine geçit *irtifakı* kuruldu.",
  "REHİN": "Borç para alan Fatma, borcuna karşılık altın bileziğini *rehin* bıraktı.",
  TAPU: "Ev, noterde imzalanan bir kâğıtla değil, ancak *tapu* müdürlüğünde yapılan satışla alıcıya geçer.",
  "TESCİL": "Satın aldığı daireyi adına *tescil* ettiren Murat, tapusunu aynı gün teslim aldı.",
  "TERKİN": "Kredi borcunu kapatan Özlem, evinin tapusundaki ipoteğin *terkin* edilmesini istedi.",
  "ŞERH": "Kiracı, kira sözleşmesini tapuya *şerh* ettirerek evin yeni sahibine karşı da korunmuş oldu.",
  KADASTRO: "*Kadastro* çalışmaları sırasında köydeki tarlaların sınırları yeniden ölçüldü.",
  "TAŞINMAZ": "Ev, arsa ve tarla gibi *taşınmazların* satışı tapu müdürlüğünde yapılır.",
  "TAŞINIR": "Bisiklet, telefon ve mobilya gibi eşyalar *taşınır* mal sayılır.",
  "İYİNİYET": "Satıcının malik olduğuna güvenerek eşyayı satın alan alıcı, *iyiniyetli* olduğu için kanunca korundu.",
  "EHLİYET": "On yaşındaki bir çocuk, fiil *ehliyeti* bulunmadığından tek başına ev satın alamaz.",
  "ERGİNLİK": "On sekiz yaşını doldurmakla *erginliğe* ulaşan kişi, kendi başına sözleşme yapabilir.",
  "GAİPLİK": "Denizde kaybolan balıkçının ailesi, mirasla ilgili işlemler için mahkemeden *gaiplik* kararı istedi.",
  HISIMLIK: "Evlenme başvurusunda eşler arasında evlenmeye engel bir *hısımlık* bulunup bulunmadığı kontrol edilir.",
  "SOYBAĞI": "Babalık davası sonucunda çocuk ile babası arasında *soybağı* kuruldu.",
  "NİŞANLANMA": "*Nişanlanmadan* sonra ayrılan çift, birbirine verdikleri hediyeleri geri istedi.",
  "BOŞANMA": "Anlaşmalı *boşanma* davasında eşler, velayet ve nafaka konusunda önceden uzlaştı.",
  TEREKE: "Mirasçılar, ölenin borçlarının *terekeden* ödenmesini istedi.",
  "MİRASÇI": "Ölen kişinin kanuni *mirasçıları*, eşi ve çocuklarıydı.",
  "TENKİS": "Bütün mallarını tek bir çocuğuna bırakan babanın diğer çocukları, saklı paylarını korumak için *tenkis* davası açtı.",
  "EDİM": "Satış sözleşmesinde satıcının *edimi* malı teslim etmek, alıcınınki ise bedeli ödemektir.",
  "İFA": "Mobilyacı, siparişi söz verdiği günde teslim ederek borcunu *ifa* etti.",
  ALACAK: "Arkadaşına bin lira borç veren Selin'in bu parayı geri isteme hakkı, onun *alacağıdır*.",
  "BORÇLU": "*Borçlu*, ödeme emrini aldıktan sonra borcunu icra dairesine yatırdı.",
  ALACAKLI: "*Alacaklı*, borcun ödenmemesi üzerine icra takibi başlattı.",
  "SÖZLEŞME": "Yeni işine başlayan Can, işvereniyle yazılı bir iş *sözleşmesi* imzaladı.",
  "İCAP": "Arabasını belirli bir fiyata satmayı teklif eden Murat'ın sözü bir *icaptır*; karşı taraf kabul ederse sözleşme kurulur.",
  KABUL: "Ev sahibinin kira teklifini *kabul* eden öğrenciyle kira sözleşmesi kurulmuş oldu.",
  "HİLE": "Kilometresi düşürülmüş arabayı satan galerici, alıcıyı *hileyle* kandırdığı için sözleşme iptal edildi.",
  MUVAZAA: "Alacaklılarından mal kaçırmak için evini kâğıt üzerinde kardeşine satan borçlunun satışı, *muvazaalı* olduğu gerekçesiyle geçersiz sayıldı.",
  BUTLAN: "Ahlaka aykırı bir amaçla yapılan sözleşme, *butlan* nedeniyle hiçbir hüküm doğurmaz.",
  "FESİH": "Ev sahibi, kirayı ödemeyen kiracıya kira sözleşmesinin *feshini* bildirdi.",
  TAKAS: "Birbirine aynı tutarda borçlu iki komşu, borçlarını *takas* ederek hesaplaştı.",
  "TEMLİK": "Şirket, müşterilerinden olan alacağını bir bankaya *temlik* etti.",
  "TEVDİ": "Ev sahibi kirayı almaktan kaçınınca kiracı, kira bedelini mahkemenin belirlediği bankaya *tevdi* etti.",
  "RÜCU": "Kazada hasarı ödeyen sigorta şirketi, kusurlu sürücüye *rücu* ederek ödediği parayı geri istedi.",
  "İFLAS": "Borçlarını ödeyemeyen tacir hakkında ticaret mahkemesi *iflas* kararı verdi.",
  KONKORDATO: "Borçlarını vadesinde ödeyemeyen şirket, iflası önlemek için *konkordato* talebinde bulundu.",
  "İCRA": "Davayı kazanan Mehmet, alacağını tahsil etmek için ilamı *icraya* koydu.",
  "İHALE": "Belediye, okul inşaatı için açtığı *ihaleyi* en uygun teklifi veren firmaya verdi.",
  "ŞÜPHELİ": "Soruşturma aşamasında *şüpheli*, müdafii eşliğinde ifade verdi.",
  SANIK: "İddianamenin kabul edilmesiyle şüpheli, artık *sanık* olarak yargılanmaya başladı.",
  "MAĞDUR": "Dolandırıcılık *mağduru* olan yaşlı adam, savcılığa suç duyurusunda bulundu.",
  "İHBAR": "Komşusunun evinden yardım çığlıkları duyan Mehmet, durumu hemen polise *ihbar* etti.",
  "ŞİKAYET": "Hakarete uğrayan Ayşe, savcılığa giderek *şikâyette* bulundu.",
  "SORUŞTURMA": "Savcılık, ihbarın ardından olayla ilgili *soruşturma* başlattı.",
  "KOVUŞTURMA": "İddianamenin mahkemece kabul edilmesiyle *kovuşturma* evresi başladı.",
  "İDDİANAME": "Soruşturmayı tamamlayan savcı, şüpheli hakkında *iddianame* düzenledi.",
  TUTUKLAMA: "Kaçma şüphesi bulunan şüpheli hakkında hâkim *tutuklama* kararı verdi.",
  "GÖZALTI": "Kavgaya karıştığı için yakalanan genç, ifadesi alınmak üzere *gözaltına* alındı.",
  YAKALAMA: "Suçüstü hâlinde herkes, kaçmaya çalışan faili *yakalama* yetkisine sahiptir.",
  "MÜSADERE": "Kaçakçılık soruşturmasında ele geçirilen sigaraların *müsaderesine* karar verildi.",
  "TEŞEBBÜS": "Kasayı açmaya çalışırken alarm çalınca kaçan kişi, hırsızlığa *teşebbüsten* yargılandı.",
  "İŞTİRAK": "Soygunu birlikte planlayıp gerçekleştiren üç kişi, suça *iştirakten* yargılandı.",
  "TEKERRÜR": "Daha önce hırsızlıktan mahkûm olan sanık yeniden suç işleyince mahkeme, *tekerrür* hükümlerini uyguladı.",
  "İNFAZ": "Hükümlünün cezasının *infazı*, kararın kesinleşmesinden sonra başladı.",
  SAVUNMA: "Sanık, duruşmada kendisine yöneltilen suçlamaya karşı avukatıyla birlikte *savunmasını* yaptı.",
  "MÜDAFİ": "Gözaltına alınan şüpheli, ifadesini ancak *müdafii* yanına geldikten sonra vereceğini söyledi.",
  "YÜRÜRLÜK": "Yeni kanun, Resmî Gazete'de yayımlandığı gün *yürürlüğe* girdi.",
  ANAYASA: "*Anayasa* Mahkemesi, anayasaya aykırı bulduğu kanun hükmünü iptal etti.",
  KANUN: "Meclis'te kabul edilen *kanun*, Resmî Gazete'de yayımlanarak yürürlüğe girdi.",
  "YÖNETMELİK": "Bakanlık, öğrenci yurtlarıyla ilgili yeni bir *yönetmelik* yayımladı.",
  "İPTAL": "Danıştay, yönetmeliğin kanuna aykırı olan maddesini *iptal* etti.",
  "KİŞİ": "Şirketler de *kişi* sayıldığı için kendi adlarına sözleşme yapabilir ve dava açabilir.",
  DEVLET: "Vatandaşların can ve mal güvenliğini sağlamak, *devletin* temel görevleri arasındadır.",
  HAK: "İnternetten aldığı ürün bozuk çıkan Zeynep, ürünü iade etme *hakkını* kullandı.",
  KARAR: "Duruşmanın sonunda hâkim *kararını* açıkladı ve taraflara başvurabilecekleri kanun yollarını bildirdi.",
  "AİLE": "Anayasaya göre *aile*, Türk toplumunun temelidir ve devlet tarafından korunur.",
  "TAKİP": "Kirası ödenmeyen ev sahibi, kiracı hakkında icra dairesinde *takip* başlattı.",
  "ŞİRKET": "Üç arkadaş, kafe açmak için sermayelerini birleştirip bir limited *şirket* kurdu.",
  TARAF: "Kira sözleşmesinin *tarafları* ev sahibi ile kiracıdır.",
  "VARİS": "Vefat eden babasının *varisleri*, mirasçılık belgesi almak için sulh hukuk mahkemesine başvurdu.",
  "İFADE": "Olayı gören yaya karakola giderek gördüklerini anlattı ve *ifadesi* tutanağa geçirildi.",
  "SUÇ": "Başkasının telefonunu izinsiz alıp götürmek hırsızlık *suçunu* oluşturur.",
  MAL: "Boşanma davasında eşler, evlilik süresince edindikleri *malların* paylaşılmasını da istedi.",
  KAYIT: "Yeni doğan bebeğin nüfus *kaydı*, ailenin başvurusuyla nüfus müdürlüğünde yapıldı.",
  "ÜCRET": "İş Kanunu'na göre işçinin *ücreti* en geç ayda bir ödenir.",
  CEZA: "Hırsızlık suçundan yargılanan sanığa mahkeme hapis *cezası* verdi.",
  ZARAR: "Üst kattaki su sızıntısı, alt kattaki dairenin tavanında *zarar* oluşturdu.",
  HUKUK: "*Hukuk* fakültesini bitiren Elif, avukat olmak için stajına başladı.",
  "İDDİA": "Davacı, arkadaşına verdiği borcu geri alamadığını *iddia* etti ve bunu banka dekontuyla kanıtladı.",
  "SATIŞ": "Arabasını satan Murat, *satış* işlemini notere giderek yaptı.",
  ADALET: "Mahkeme salonlarındaki \"*Adalet* mülkün temelidir\" yazısı, devletin adalet üzerine kurulduğunu hatırlatır.",
  MAHKEME: "Anlaşamayan iki komşu, aralarındaki sınır uyuşmazlığını çözmesi için *mahkemeye* başvurdu.",
  "HÜKÜMET": "*Hükümet*, artan fiyatlara karşı yeni ekonomik tedbirler açıkladı.",
  "İŞLEM": "Kiracının sözleşmeyi feshettiğini ev sahibine bildirmesi, tek taraflı bir hukuki *işlemdir*.",
  "İDARE": "Belediyenin onarmadığı kaldırımda düşüp yaralanan vatandaş, *idareye* karşı tazminat davası açtı.",
  "ÇEK": "Müşterisinden aldığı *çeki* bankaya götüren esnaf, çekin bedelini tahsil etti.",
  "DEVİR": "Dükkânını başkasına devreden esnaf, kira sözleşmesinin *devri* için ev sahibinin yazılı onayını aldı.",
  "ŞART": "Baba, \"Üniversiteyi bitirirsen sana araba alacağım\" diyerek bağışlamayı bir *şarta* bağladı.",
  "İMZA": "Banka, kredi sözleşmesinin her sayfasının müşteri tarafından *imzalanmasını* istedi.",
  TERK: "Ortak evi haklı bir sebep olmadan *terk* eden ve ihtara rağmen dönmeyen eşe karşı boşanma davası açılabilir.",
  KAMU: "Parklar, meydanlar ve yollar *kamunun* ortak kullanımına açık yerlerdir.",
  KUSUR: "Kırmızı ışıkta geçen sürücü, kazanın meydana gelmesinde tam *kusurlu* bulundu.",
  MEMUR: "Sınavı kazanıp atanan Burak, vergi dairesinde *memur* olarak çalışmaya başladı.",
  "HAKİM": "Duruşmayı yöneten *hâkim*, tanıkları tek tek dinledikten sonra kararını verdi.",
  TALEP: "Davacı, dilekçesinde uğradığı zararın faiziyle birlikte ödenmesini *talep* etti.",
  "BORÇ": "Bankadan kredi çeken Aylin, *borcunu* her ay taksitlerle ödüyor.",
  "VERGİ": "Serbest çalışan avukat, yıllık kazancı üzerinden gelir *vergisi* ödedi.",
  VAKIF: "Varlıklı bir iş insanı, öğrencilere burs vermek amacıyla bir *vakıf* kurdu.",
  "İSTİFA": "Başka bir şirketten iş teklifi alan Deniz, mevcut işinden *istifa* etti.",
  "ARAZİ": "Köydeki *arazisine* zeytin ağacı diken çiftçi, ilk hasadı gelecek yıl bekliyor.",
  YARGI: "Anayasaya göre *yargı* yetkisi, Türk Milleti adına bağımsız mahkemelerce kullanılır.",
  HIRSIZ: "Kameralar sayesinde *hırsız*, çaldığı bisikletle birlikte kısa sürede yakalandı.",
  "SUÇLU": "Mahkeme kararıyla *suçlu* bulunan kişi, hapis cezasına çarptırıldı.",
  SAVCI: "Olay yerine gelen *savcı*, delillerin toplanması için talimat verdi.",
  PAY: "Üç kardeş, babalarından kalan evde eşit *paylara* sahip oldu.",
  MAHKUM: "On yıl hapis cezasına çarptırılan *mahkûm*, cezaevine gönderildi.",
  "VEKİL": "Yurt dışında yaşayan Emre, evinin satışı için kardeşini noterde *vekil* tayin etti.",
  SORUMLULUK: "Kiracının kullanımı sırasında kırılan cam, kiracının *sorumluluğundadır*.",
  "SİGORTA": "Kaza sonrası aracındaki hasarı kasko *sigortası* karşıladı.",
  "BAŞVURU": "Bireysel *başvuru* yolunu kullanan vatandaş, hakkının ihlal edildiğini Anayasa Mahkemesine bildirdi.",
  "FAİZ": "Ödemeyi geciktiren borçlu, geciktiği süre için *faiz* ödemek zorunda kaldı.",
  "CEZAEVİ": "Hapis cezası kesinleşen hükümlü, *cezaevine* teslim oldu.",
  "HAZİNE": "Sahibi bulunamayan taşınmazlar, kadastro sırasında *Hazine* adına tapuya tescil edildi.",
  TUTUKLU: "*Tutuklu* sanık, duruşmaya cezaevinden getirildi.",
  "ŞAHİT": "Olay gecesi kavgayı gören garson, mahkemede *şahit* olarak dinlendi.",
  "HİSSE": "Borsada işlem gören şirketin *hisselerinden* alan yatırımcı, şirketin ortağı oldu.",
  "DENETİM": "Sayıştay, belediyenin harcamalarını yıllık *denetimde* inceledi.",
  FATURA: "Mağazadan buzdolabı alan Hülya, garanti için *faturasını* sakladı.",
  "VELİ": "Okul kaydı için öğrencinin *velisinin* imzası istendi.",
  "KİRA": "Ayşe, oturduğu dairenin *kirasını* her ayın beşinde ev sahibinin hesabına yatırıyor.",
  "DİSİPLİN": "Göreve sürekli geç gelen memur hakkında *disiplin* soruşturması açıldı.",
  ORTAKLIK: "İki kardeş, babalarından kalan dükkân üzerindeki *ortaklığın* giderilmesi için dava açtı.",
  "ADLİYE": "Duruşma saatinden önce *adliyeye* gelen avukat, dosyasını incelemeye başladı.",
  SENET: "Borç verdiği arkadaşından imzalı bir *senet* alan Kemal, alacağını güvenceye aldı.",
  MUHTAR: "Mahalledeki sokak lambalarının yanmadığını fark eden *muhtar*, durumu belediyeye bildirdi.",
  "MÜLK": "Yıllarca kirada oturan Ahmet, sonunda kendi *mülkü* olan bir daire satın aldı.",
  SORGU: "Duruşmada hâkim, sanığın *sorgusunu* yaparak ona olay gecesini sordu.",
  YARGITAY: "Bölge adliye mahkemesinin kararı, temyiz üzerine *Yargıtay* tarafından incelendi.",
  SAVCILIK: "Dolandırıcılığa uğrayan Nihat, *savcılığa* suç duyurusunda bulundu.",
  "YARGIÇ": "Davayı gören *yargıç*, tarafları anlaşmaya davet etti.",
  GREV: "Toplu sözleşme görüşmelerinden sonuç alamayan sendika, *grev* kararı aldı.",
  "MÜHÜR": "Kaçak yapılan inşaat, belediye ekiplerince *mühürlenerek* faaliyeti durduruldu.",
  "İFTİRA": "Komşusunu suçsuz olduğunu bildiği hâlde hırsızlıkla suçlayan kişi, *iftira* suçundan yargılandı.",
  ZANLI: "Polis, olay yerinden kaçan *zanlıyı* kamera kayıtlarıyla tespit etti.",
  ARSA: "Müteahhit, *arsa* sahibiyle anlaşarak arsanın üzerine apartman yapmaya başladı.",
  NOTER: "Yurt dışına çıkacak olan Selim, işlerini kardeşine bırakmak için *noterden* vekâletname çıkardı.",
  "GARDİYAN": "Ziyaret saatinde *gardiyan*, ziyaretçilerin üst aramasını yaptı.",
  "HÜKÜMLÜ": "Cezası kesinleşen *hükümlü*, iyi hâli nedeniyle açık cezaevine geçirildi.",
  HATA: "Antika sanarak yüksek fiyata aldığı vazonun yeni çıkması üzerine Kenan, *hataya* dayanarak sözleşmeyle bağlı olmadığını bildirdi.",
  "ŞÜPHE": "Delillerin yetersiz kalması üzerine mahkeme, \"*Şüpheden* sanık yararlanır\" ilkesini uyguladı.",
  "TEMSİLCİ": "Şirketin yasal *temsilcisi* olan müdür, sözleşmeyi şirket adına imzaladı.",
  KATILAN: "Kamu davası açıldıktan sonra mağdur, davaya *katılan* olarak dahil oldu.",
  "İŞGAL": "Komşusunun bahçesine izinsiz çit çeken kişi, araziyi haksız *işgal* ettiği gerekçesiyle dava edildi.",
  "TECAVÜZ": "Komşusunun duvarını izinsiz yıkan kişi, onun mülkiyet hakkına *tecavüz* etmiş oldu.",
  USUL: "Dava şartı eksik olduğu için mahkeme, davayı esasa girmeden *usulden* reddetti.",
  "HAMİL": "Çekin *hamili*, bankaya giderek çek bedelini istedi.",
  "İRADE": "Korkutularak imzalatılan sözleşme, tarafın gerçek *iradesini* yansıtmadığı için iptal edilebilir.",
  "İADE": "Kira sözleşmesi bitince ev sahibi, kiracının depozitosunu *iade* etti.",
  "İHRAÇ": "Dernek tüzüğünü ağır biçimde ihlal eden üye, dernekten *ihraç* edildi.",
  REFERANDUM: "Anayasa değişikliği, *referandumda* halkın oyuna sunuldu.",
  "TEŞHİS": "Mağdur, karakolda kendisine gösterilen kişiler arasından saldırganı *teşhis* etti.",
  "İHLAL": "Avukat, müvekkilinin özel hayatının gizliliği hakkının *ihlal* edildiğini ileri sürdü.",
  "TEDBİR": "Dava sürerken evin satılmasını önlemek için mahkeme, tapuya *tedbir* konulmasına karar verdi.",
  "TAKSİM": "Mirasçılar, babalarından kalan tarlayı aralarında anlaşarak *taksim* etti.",
  VADE: "Bononun *vadesi* geldiğinde borçlu ödemeyi yapmak zorundadır.",
  KIYAS: "Ceza hukukunda suç ve cezalar konusunda *kıyas* yapılamaz.",
  BATIL: "Kanunun açıkça yasakladığı bir konuda yapılan sözleşme, hukuken *batıl* sayılır.",
  "FİİL": "Kişi, yalnızca kanunun açıkça suç olarak tanımladığı bir *fiil* nedeniyle cezalandırılabilir.",
  "İHMAL": "Küçük çocuğunu günlerce bakımsız bırakan ebeveyn, bakım yükümlülüğünü *ihmal* etmiş sayıldı.",
  "TAHRİK": "Ağır bir hakarete uğradıktan sonra öfkeyle karşılık veren sanığa mahkeme, haksız *tahrik* indirimi uyguladı.",
  EVRAK: "Avukat, dava dosyasındaki bütün *evrakı* tek tek inceledi.",
  "DEFİN": "Hastanede vefat eden kişinin *defin* ruhsatı alındıktan sonra cenaze töreni yapıldı.",
  "TASFİYE": "Faaliyetini durduran şirket, borçlarını ödeyip alacaklarını topladıktan sonra *tasfiye* edildi.",
  HAVALE: "Kirasını bankadan ev sahibinin hesabına *havale* eden kiracı, dekontu sakladı.",
  "İMAR": "*İmar* planında yeşil alan olarak gösterilen yere bina yapılamaz.",
  "TELİF": "Şarkısı izinsiz olarak reklamda kullanılan besteci, *telif* hakkının ihlal edildiğini ileri sürdü.",
  "TAHSİS": "Belediye, mahalledeki boş alanı çocuk parkı yapılmak üzere *tahsis* etti.",
  TASARRUF: "Evini kızına bağışlayan anne, ev üzerinde bir *tasarruf* işlemi yapmış oldu.",
  KARARNAME: "Atama işlemi, Resmî Gazete'de yayımlanan bir *kararnameyle* yapıldı.",
  TASARI: "Hazırlanan vergi *tasarısı*, Meclis'te tartışmaya açıldı.",
  FIKRA: "Avukat, dilekçesinde kanunun ilgili maddesinin ikinci *fıkrasına* dayandı.",
  PARSEL: "Ali, köyündeki 112 ada 5 *parsel* numaralı tarlanın tapusunu aldı.",
  "FAİL": "Kamera kayıtları incelenince olayın *faili* kısa sürede belirlendi.",
  "İFŞA": "Hastanın sağlık bilgilerini izinsiz paylaşan çalışan, kişisel verileri *ifşa* etmekle suçlandı.",
  MUHATAP: "İhtarnamenin *muhatabı* olan kiracı, bildirimi aldığını imzasıyla onayladı.",
  "UZLAŞMA": "Kira artışı konusunda anlaşamayan taraflar, sonunda orta bir rakamda *uzlaşmaya* vardı.",
  "ŞİKAYETÇİ": "Telefonu çalınan Merve, karakola giderek failden *şikâyetçi* oldu.",
  "HARÇ": "Dava açan kişi, mahkeme veznesine başvurma *harcını* yatırmak zorundadır.",
  "MÜEBBET": "Ağır bir suçtan yargılanan sanığa *müebbet* hapis cezası verildi.",
  "EKLENTİ": "Evin satışına, evin *eklentisi* olan kömürlük ve garaj da dahil edildi.",
  "REŞİT": "On sekiz yaşını dolduran Ece, *reşit* olduğu için kendi adına kira sözleşmesi imzalayabildi.",
  "MALİK": "Tapuda adı yazan Hakan, dairenin tek *maliki* olarak görünüyor.",
  KONTRAT: "Yeni eve taşınan öğrenci, ev sahibiyle bir yıllık *kontrat* imzaladı.",
  GASP: "Yolda zorla telefonu alınan genç, *gasp* olayını hemen polise bildirdi.",
  RUHSAT: "Restoran açmak isteyen Mert, belediyeden işyeri açma *ruhsatı* aldı.",
  "TEMİNAT": "Mahkeme, ihtiyati haciz kararı verirken alacaklıdan *teminat* göstermesini istedi.",
  "TEBLİĞ": "Dava dilekçesi davalıya *tebliğ* edildikten sonra cevap süresi işlemeye başladı.",
  "TÜZEL": "Dernekler ve şirketler *tüzel* kişi oldukları için kendi adlarına mal edinebilir.",
  "TAHSİL": "Vergi dairesi, süresinde ödenmeyen vergiyi gecikme zammıyla birlikte *tahsil* etti.",
  MENKUL: "Mirasa kalan araba ve mücevherler, terekedeki *menkul* mallardır.",
  "AKİT": "Taraflar, satış *akdini* noterde imzaladı.",
  "SİCİL": "Yeni kurulan şirket, ticaret *siciline* tescil edildi.",
  "ZİNA": "Eşinin *zina* yaptığını öğrenen kişi, bu sebebe dayanarak boşanma davası açtı.",
  KOLLUK: "İhbarı alan *kolluk* görevlileri, birkaç dakika içinde olay yerine ulaştı.",
  "MÜDAFAA": "Saldırıya uğrayan kişinin kendini korumak için yaptığı hareket, meşru *müdafaa* kabul edildi.",
  "KATİP": "Duruşma sırasında mahkeme *kâtibi*, tarafların beyanlarını tutanağa geçirdi.",
  "ŞAHSİYET": "Kişinin adı, onuru ve özel hayatı, *şahsiyet* hakları kapsamında korunur.",
  "İMTİYAZ": "Anayasaya göre hiçbir kişiye, aileye, zümreye veya sınıfa *imtiyaz* tanınamaz.",
  "İTHAM": "Sanık, kendisine yöneltilen *itham* karşısında suçsuz olduğunu söyledi.",
  "TÜZÜK": "Eskiden kanunların uygulanmasını göstermek için Bakanlar Kurulu tarafından *tüzük* çıkarılırdı.",
  "FUHUŞ": "Kanun, bir kimseyi *fuhşa* teşvik etmeyi veya buna aracılık etmeyi suç olarak düzenler.",
  BEYANNAME: "Serbest çalışan mimar, yıllık gelir vergisi *beyannamesini* mart ayında verdi.",
  ERTELEME: "Mahkeme, ilk kez suç işleyen sanığın kısa süreli hapis cezasının *ertelenmesine* karar verdi.",
  "TASDİK": "Yurt dışında kullanılacak diploma, noterde *tasdik* ettirildi.",
  "RÜŞT": "On sekiz yaşına girerek *rüştünü* ispat eden genç, mirasını kendisi yönetmeye başladı.",
  "HİBE": "Baba, oğluna arabasını *hibe* ederek karşılıksız olarak devretti.",
  "MUAFİYET": "Engelli bireylerin araç alımında bazı vergilerden *muafiyet* tanınır.",
  MEVZUAT: "Yeni işe başlayan avukat, iş hukukuyla ilgili *mevzuatı* baştan sona inceledi.",
  ZABITA: "Kaldırımı işgal eden seyyar satıcıya belediye *zabıtası* ceza yazdı.",
  "TAAHHÜT": "Müteahhit, binayı iki yıl içinde teslim etmeyi *taahhüt* etti.",
  KAYYUM: "Uzun süredir haber alınamayan kişinin mallarını yönetmesi için mahkeme bir *kayyum* atadı.",
  "İLTİCA": "Ülkesindeki savaştan kaçan aile, Türkiye'ye *iltica* başvurusunda bulundu.",
  "MÜTEAHHİT": "Arsa sahibi, apartmanı yapmak için bir *müteahhitle* kat karşılığı inşaat sözleşmesi imzaladı.",
  MUTABAKAT: "Yıl sonunda iki şirket, karşılıklı borç ve alacaklarını gösteren *mutabakat* belgesini imzaladı.",
  VETO: "Bazı ülkelerde devlet başkanı, meclisin kabul ettiği bir kanunu *veto* ederek yürürlüğe girmesini engelleyebilir.",
  EMSAL: "Avukat, benzer bir davada Yargıtay'ın verdiği *emsal* kararı dilekçesine ekledi.",
  "İNTİKAL": "Babasının vefatıyla tarla, mirasçılara *intikal* etti.",
  "CEBİR": "Telefonunu vermek istemeyen gence *cebir* kullanan saldırgan, yağma suçundan yargılandı.",
  "SAYIŞTAY": "*Sayıştay*, bakanlığın yıllık harcamalarını denetleyerek raporunu Meclis'e sundu.",
  "UYUŞMAZLIK": "Kiracı ile ev sahibi arasındaki kira artışı *uyuşmazlığı* önce arabulucuya götürüldü.",
  MERA: "Köyün *merasına* izinsiz ev yapan kişinin yapısı yıkıldı.",
  BONO: "Arabayı taksitle satan galerici, alıcıdan her taksit için bir *bono* aldı.",
  "POLİÇE": "Trafik sigortası yaptıran Nur, sigorta *poliçesini* aracında taşıyor.",
  "TACİR": "Kendi adına market işleten Hüseyin, *tacir* olduğu için ticari defter tutmak zorundadır.",
  "CİRO": "Elindeki çeki arkasını imzalayarak tedarikçisine *ciro* eden esnaf, borcunu böylece ödedi.",
  TUTANAK: "Kazadan sonra iki sürücü, olayı anlatan kaza tespit *tutanağını* birlikte doldurdu.",
  "MÜVEKKİL": "Avukat, *müvekkilini* duruşmanın sonucu hakkında bilgilendirdi.",
  MUHAKEME: "Adil yargılanma hakkı, herkesin bağımsız ve tarafsız bir mahkemede *muhakeme* edilmesini güvence altına alır.",
  VERASET: "Ölen babalarının mallarını almak isteyen kardeşler, önce *veraset* ilamı çıkardı.",
  "MURİS": "*Murisin* ölümüyle birlikte mirası, kanuni mirasçılarına geçti.",
  "MÜZAYEDE": "Ünlü ressamın tablosu, *müzayedede* beklenenden yüksek bir fiyata satıldı.",
  "ZİMMET": "Belediyenin kasasındaki parayı kendi hesabına aktaran memur, *zimmet* suçundan yargılandı.",
  "MÜKELLEF": "Kira geliri elde etmeye başlayan Ayten, gelir vergisi *mükellefi* oldu.",
  MUHTIRA: "Sendika, çalışma koşullarıyla ilgili taleplerini bir *muhtırayla* bakanlığa iletti.",
  "İNTİHAL": "Başka birinin makalesini kaynak göstermeden tezine kopyalayan öğrenci, *intihal* nedeniyle disiplin cezası aldı.",
  "İHTAR": "Kirasını iki aydır ödemeyen kiracıya ev sahibi, noter aracılığıyla *ihtar* çekti.",
  "VASİ": "Kısıtlanan yaşlı adamın işlerini yürütmek için mahkeme, oğlunu *vasi* olarak atadı.",
  "DEPOZİTO": "Ev sahibi, kiracıdan iki aylık kira tutarında *depozito* aldı.",
  "MOBBİNG": "Yöneticisi tarafından sürekli aşağılanan çalışan, *mobbing* gerekçesiyle tazminat davası açtı.",
  LOKAVT: "İşçilerin greve çıkmasının ardından işveren, *lokavt* ilan ederek işyerini kapattı.",
  "ŞARTNAME": "İhaleye girmek isteyen firma, işin ayrıntılarını gösteren *şartnameyi* inceledi.",
  "İLMÜHABER": "Mahalle muhtarından alınan *ilmühaber*, kişinin o adreste oturduğunu gösterir.",
  PAFTA: "Tapu müdürlüğü, tarlanın yerini *paftası* üzerinde gösterdi.",
  MUKAVELE: "Sanatçı, konser organizatörüyle iki yıllık bir *mukavele* imzaladı.",
  ONAMA: "Yargıtay'ın *onama* kararıyla yerel mahkemenin hükmü kesinleşti.",
  "İKAMETGAH": "Yeni şehre taşınan Selin, *ikametgâh* adresini nüfus müdürlüğünde güncelletti.",
  "AZİL": "Davayı iyi takip etmediğini düşünen müvekkil, avukatını *azletti*.",
  MAZBATA: "Seçimi kazanan belediye başkanı, *mazbatasını* ilçe seçim kurulundan aldı.",
  ACENTA: "Sigorta şirketinin *acentası*, müşterilere poliçe düzenleyip satış yapıyor.",
  "MÜBAŞİR": "Duruşma saati gelince *mübaşir*, tarafların adlarını koridorda seslendi.",
  "İRAT": "Emekli öğretmen, kiraya verdiği iki dairenin getirdiği *iratla* geçiniyor.",
  YOKLUK: "Hiç seçilmemiş bir kişinin imzaladığı belediye kararı, *yokluk* ile sakat sayılır.",
  EDA: "Alacaklı, borcun ödenmesi için davalı aleyhine *eda* davası açtı.",
  "TEFSİR": "Hâkim, kanun maddesinin belirsiz ifadesini kanunun amacına göre *tefsir* etti.",
  "ACİZ": "Haciz sırasında borçlunun hiç malı bulunamayınca alacaklıya *aciz* belgesi verildi.",
  "MÜTEVELLİ": "Vakfın *mütevelli* heyeti, yeni burs dönemini görüşmek için toplandı.",
  "DEFİ": "Davalı, alacağın zamanaşımına uğradığını ileri sürerek zamanaşımı *definde* bulundu.",
  HASILAT: "Kafenin yaz aylarındaki *hasılatı*, kış aylarının iki katına çıktı.",
  "MÜDAHİL": "Davanın sonucundan etkilenecek olan şirket, davacının yanında *müdahil* olarak davaya katıldı.",
  "SAHİH": "Noterde usulüne uygun düzenlenen vasiyetname *sahih* kabul edildi.",
  "TAHRİR": "Mahkeme kâtibi, tanığın sözlerini olduğu gibi tutanağa *tahrir* etti.",
  "REPLİK": "Davalının cevap dilekçesini alan davacı, iki hafta içinde *replik* dilekçesini verdi.",
  MECRA: "Komşunun bahçesinden geçen su *mecrası*, iki ev arasında anlaşmazlığa yol açtı.",
  HALEF: "Şirketi devralan yeni şirket, eski şirketin *halefi* olarak borçlarından da sorumlu oldu.",
  "ZAYİ": "Cüzdanı çalınan Kerem, *zayi* olan kimliği için nüfus müdürlüğüne başvurdu.",
  "İCAZET": "Yetkisi olmadan kardeşi adına sözleşme yapan Can'ın işlemi, kardeşinin sonradan verdiği *icazetle* geçerlilik kazandı.",
  "FUZULİ": "Komşusunun bahçesini izinsiz kullanan kişi, *fuzuli* şagil olarak ecrimisil ödemek zorunda kaldı.",
  "TAHKİKAT": "Müfettişler, kurumdaki usulsüzlük iddialarıyla ilgili *tahkikat* başlattı.",
  MECUR: "Kiracı, *mecuru* sözleşme bitiminde aldığı gibi geri vermekle yükümlüdür.",
  "İSNAT": "Sanığa *isnat* edilen suç, iddianamede ayrıntılı olarak açıklandı.",
  AVAL: "Şirketin verdiği bonoya patronu *aval* vererek ödemeyi güvence altına aldı.",
  HUSUMET: "Davanın yanlış kişiye karşı açıldığını gören mahkeme, davayı *husumet* yokluğundan reddetti.",
  FEZLEKE: "Soruşturmayı tamamlayan polis, olayı özetleyen *fezlekeyi* savcılığa gönderdi.",
  HASIM: "Duruşmada iki *hasım* taraf, avukatları aracılığıyla görüşlerini sundu.",
  "İSTİMLAK": "Yeni otoyol için idare, yol güzergâhındaki tarlaları *istimlak* etti.",
  "İBRAZ": "Hamil, çeki keşide gününden itibaren on gün içinde bankaya *ibraz* etti.",
  "İKTİSAP": "Yabancı uyruklu yatırımcı, İstanbul'da bir daire *iktisap* etti.",
  DONATAN: "Geminin batmasından doğan zararlar için yük sahipleri *donatana* karşı dava açtı.",
  "TESELSÜL": "Sözleşmede *teselsül* şartı bulunduğundan banka, borcun tamamını ortaklardan herhangi birinden isteyebildi.",
  NAVLUN: "İhracatçı, malların gemiyle taşınması için taşıyıcıya *navlun* ödedi.",
  RESEN: "Hâkim, taraflar istemese de dava şartlarını *resen* inceledi.",
  ZIYA: "Vergi beyannamesini eksik veren şirket hakkında vergi *ziyaı* cezası kesildi.",
  "ZİLYET": "Ev sahibi yurt dışındayken evde oturan kiracı, evin *zilyedidir*.",
  MUACCEL: "Vadesi dolan borç *muaccel* hâle geldiği için alacaklı ödemeyi isteyebildi.",
  TAHAKKUK: "Vergi dairesinin hesapladığı vergi, itiraz süresi geçince *tahakkuk* etti.",
  TARH: "Vergi dairesi, beyannameye göre şirketin vergisini *tarh* etti.",
  "MÜFLİS": "İflas eden şirketin, yani *müflisin* malları alacaklılar için satışa çıkarıldı.",
  MAHSUP: "Vergi dairesi, iade edilecek tutarı şirketin diğer vergi borcundan *mahsup* etti.",
  "RİZİKO": "Deprem sigortası, depremin yol açtığı hasar *rizikosunu* güvence altına alır.",
  LEHTAR: "Bonoda adı yazan *lehtar*, vade geldiğinde ödemeyi talep etti.",
  MUVAFAKAT: "Küçük çocuğun yurt dışına çıkabilmesi için ebeveyninin *muvafakati* istendi.",
  "İSTİHKAK": "Kiracının evinde yapılan hacizde koltuğun kendisine ait olduğunu söyleyen ev sahibi, *istihkak* iddiasında bulundu.",
  VAKIA: "Davacı, dilekçesinde kazanın nasıl olduğunu gösteren *vakıaları* sırasıyla anlattı.",
  MATRAH: "Kira geliri elde eden Leyla'nın vergisi, yıllık kira gelirinden oluşan *matrah* üzerinden hesaplandı.",
  "MÜTESELSİL": "Kredi sözleşmesinde *müteselsil* kefil olan kişiden banka, borcun tamamını doğrudan isteyebilir.",
  "RAYİÇ": "Ev satılırken taşınmazın piyasadaki *rayiç* değeri araştırıldı.",
  "İTFA": "Borçlu, son taksiti de ödeyerek borcunu tamamen *itfa* etti.",
  "NİSAP": "Toplantı yeter sayısı, yani *nisap* sağlanamadığı için kurul karar alamadı.",
  "KAMBİYO": "Çek, bono ve poliçeye dayanan alacaklar için icra dairesinde *kambiyo* senetlerine özgü bir takip yolu vardır.",
  "MÜCBİR": "Deprem nedeniyle teslimatı yapamayan firma, *mücbir* sebep bulunduğunu ileri sürerek sorumluluktan kurtuldu.",
  "CİRANTA": "Çek karşılıksız çıkınca hamil, çeki kendisine ciro eden *cirantaya* da başvurdu.",
  "İSTİNABE": "İzmir'de görülen davada İstanbul'da yaşayan tanık, *istinabe* yoluyla İstanbul'daki mahkemede dinlendi.",
  "RÜÇHAN": "Şirketin yeni pay çıkarmasında eski ortaklar, *rüçhan* haklarını kullanarak öncelikle pay aldı.",
  "TEAMÜL": "İşyerinde yıllardır her bayram ikramiye verilmesi, işçiler lehine bir *teamül* oluşturdu.",
  "TEFHİM": "Hâkim, kısa kararı duruşmada taraflara *tefhim* etti.",
  "MÜMESSİL": "Yabancı şirketin Türkiye *mümessili*, sözleşmeleri şirket adına imzalıyor.",
  "İSTİCVAP": "Mahkeme, olayı en iyi davalının bildiğini düşünerek onun *isticvabına* karar verdi.",
  "TEVSİK": "Vergi incelemesinde şirket, giderlerini faturalarla *tevsik* etti.",
  "İFRAZ": "Büyük tarlasını üç çocuğuna paylaştırmak isteyen çiftçi, parselin *ifrazı* için başvurdu.",
  "İMTİNA": "Sanığın kardeşi, kanunun tanıdığı hakkı kullanarak tanıklıktan *imtina* etti.",
  "GAİP": "Uçak kazasından sonra kendisinden haber alınamayan yolcu, mahkeme kararıyla *gaip* sayıldı.",
  HISIM: "Kanuna göre kişi, yakın kan *hısımlarından* biriyle evlenemez.",
  MAHCUZ: "*Mahcuz* araba, icra dairesinin düzenlediği açık artırmayla satıldı.",
  "TEVKİL": "Avukat, vekâletnamesindeki yetkiye dayanarak dosyayı meslektaşına *tevkil* etti.",
  MAKTU: "Bazı belgeler için alınan harç, belgedeki tutara bakılmaksızın *maktu* olarak belirlenir.",
  "TALİK": "Baba, evi bağışlamasını oğlunun evlenmesi şartına *talik* etti ve düğünden sonra evi devretti.",
  "TEDAVÜL": "Eski banknotlar, Merkez Bankası kararıyla *tedavülden* kaldırıldı.",
  "MÜTALAA": "Savcı, esas hakkındaki *mütalaasında* sanığın cezalandırılmasını istedi.",
  "YEDİEMİN": "Hacizle alınan araç, satışa kadar korunmak üzere bir *yediemin* otoparkına çekildi.",
  "TADİL": "Taraflar, kira sözleşmesinin süresini uzatmak için sözleşmeyi *tadil* etti.",
  TRAMPA: "Arabasını komşusunun motosikletiyle *trampa* eden Okan, aradaki farkı nakit ödedi.",
  "İVAZ": "Satış sözleşmesinde malın *ivazı*, alıcının ödediği bedeldir.",
  "TAVZİH": "Kararın hangi taşınmazı kapsadığı anlaşılamayınca taraf, mahkemeden kararın *tavzihini* istedi.",
  "İSTİRDAT": "Borcu olmadığı hâlde icra tehdidiyle ödeme yapan kişi, parasını geri almak için *istirdat* davası açtı.",
  "MÜKERRİR": "Cezası kesinleştikten sonra yeniden suç işleyen *mükerrir*, cezasını özel bir infaz rejimiyle çekti.",
  DERDEST: "Aynı konuda başka bir mahkemede *derdest* dava bulunduğu için ikinci dava reddedildi.",
  "MÜELLİF": "Kitabın *müellifi*, eserinin izinsiz basıldığını öğrenince yayınevine dava açtı.",
  "İLGA": "Yeni kanun yürürlüğe girince eski kanun *ilga* edildi.",
  EMARE: "Olay yerinde bulunan ayak izleri, şüphelinin orada bulunduğuna dair güçlü bir *emare* sayıldı.",
  "İRTİKAP": "Ruhsat vermek için iş insanından para isteyen memur, *irtikap* suçundan yargılandı.",
  "TEBELLÜĞ": "Dava dilekçesini *tebellüğ* eden davalı, iki hafta içinde cevap verdi.",
  MUHAMMEN: "İhalede arsanın *muhammen* bedeli bir milyon lira olarak açıklandı.",
  "HALEFİYET": "Hasarı ödeyen sigorta şirketi, *halefiyet* ilkesi gereği sigortalının yerine geçerek kusurlu kişiye başvurdu.",
  CELSE: "Dava, üçüncü *celsede* tanıkların dinlenmesiyle devam etti.",
  "TAHKİK": "Mahkeme, iddiaların doğruluğunu *tahkik* etmek için ilgili kurumlardan bilgi istedi.",
  "MEHİL": "Hâkim, eksik belgelerin tamamlanması için davacıya iki haftalık *mehil* verdi.",
  "SİMSARLIK": "Evin satışına aracılık eden emlakçı, *simsarlık* ücreti olarak komisyon aldı.",
  "ÖNEL": "Ev sahibi, kiracıya evi boşaltması için otuz günlük *önel* verdi.",
  "TEHİR": "Borçlu, kararı istinafa taşıyıp teminat yatırarak icranın *tehiri* kararı aldı.",
};
