// Terms that belong to more than one field of law, with every category they belong to.
// Every other term belongs only to the category written in its question.
export const termCategories: Record<string, string[]> = {
  ZİLYETLİK: ["Medeni", "Eşya"],
  İBRA: ["Borçlar", "İş"],
  TEMYİZ: ["Usul", "Ceza", "İdare"],
  İSTİNAF: ["Usul", "Ceza", "İdare"],
  TEBLİGAT: ["Usul", "İcra", "İdare"],
  VEKALET: ["Borçlar", "Usul"],
  TAZMİNAT: ["Borçlar", "İş"],
  TAHLİYE: ["Borçlar", "İcra"],
  İÇTİHAT: ["Genel", "Usul"],
  ZAMANAŞIMI: ["Borçlar", "Ceza"],
  İPOTEK: ["Eşya", "İcra"],
  KEFALET: ["Borçlar", "Ticaret"],
  VESAYET: ["Medeni", "Aile"],
  DELİL: ["Usul", "Ceza"],
  TANIK: ["Usul", "Ceza"],
  BİLİRKİŞİ: ["Usul", "Ceza"],
  HÜKÜM: ["Usul", "Ceza"],
  İLAM: ["Usul", "İcra"],
  DURUŞMA: ["Usul", "Ceza"],
  DİLEKÇE: ["Usul", "İdare"],
  KEŞİF: ["Usul", "Ceza"],
  TAHKİM: ["Usul", "Ticaret"],
  HAKEM: ["Usul", "Ticaret"],
  İTİRAZ: ["Usul", "İcra", "Ceza"],
  MÜLKİYET: ["Eşya", "Anayasa"],
  REHİN: ["Eşya", "İcra"],
  TESCİL: ["Eşya", "Ticaret"],
  KADASTRO: ["Eşya", "İdare"],
  İYİNİYET: ["Medeni", "Eşya", "Borçlar"],
  GAİPLİK: ["Medeni", "Miras"],
  HISIMLIK: ["Medeni", "Aile"],
  ALACAK: ["Borçlar", "İcra"],
  BORÇLU: ["Borçlar", "İcra"],
  ALACAKLI: ["Borçlar", "İcra"],
  FESİH: ["Borçlar", "İş"],
  RÜCU: ["Borçlar", "Ticaret"],
  İFLAS: ["İcra", "Ticaret"],
  KONKORDATO: ["İcra", "Ticaret"],
  İHALE: ["Genel", "İdare"],
  SAVUNMA: ["Genel", "Ceza", "Usul"],
  İPTAL: ["Genel", "İdare"],
  DEVLET: ["Anayasa", "İdare"],
  MAL: ["Eşya", "Aile"],
  HÜKÜMET: ["Anayasa", "İdare"],
  KUSUR: ["Borçlar", "Ceza"],
  HAKİM: ["Usul", "Ceza"],
  İSTİFA: ["İş", "İdare"],
  YARGI: ["Anayasa", "Usul"],
  ŞAHİT: ["Usul", "Ceza"],
  FATURA: ["Vergi", "Ticaret"],
  DİSİPLİN: ["İdare", "İş"],
  SENET: ["Borçlar", "Ticaret"],
  YARGITAY: ["Usul", "Ceza"],
  YARGIÇ: ["Usul", "Ceza"],
  GREV: ["İş", "Anayasa"],
  TECAVÜZ: ["Ceza", "Eşya"],
  TAKSİM: ["Eşya", "Miras"],
  KIYAS: ["Genel", "Ceza"],
  FİİL: ["Genel", "Ceza"],
  TASFİYE: ["Ticaret", "İcra"],
  İMAR: ["İdare", "Eşya"],
  TASARRUF: ["Medeni", "Eşya"],
  KARARNAME: ["Anayasa", "İdare"],
  HARÇ: ["Vergi", "Usul"],
  TEMİNAT: ["Borçlar", "İcra"],
  TEBLİĞ: ["Usul", "İcra"],
  TÜZEL: ["Medeni", "Ticaret"],
  TAHSİL: ["İcra", "Vergi"],
  SİCİL: ["Genel", "Ticaret", "Eşya"],
  KOLLUK: ["Ceza", "İdare"],
  İMTİYAZ: ["Anayasa", "Ticaret"],
  KAYYUM: ["Medeni", "Aile"],
  İNTİKAL: ["Miras", "Vergi"],
  SAYIŞTAY: ["İdare", "Anayasa"],
  MERA: ["Eşya", "İdare"],
  MUHAKEME: ["Usul", "Ceza"],
  VERASET: ["Miras", "Vergi"],
  MÜZAYEDE: ["Ticaret", "İcra"],
  ZİMMET: ["Ceza", "İdare"],
  VASİ: ["Medeni", "Aile"],
  ONAMA: ["Usul", "Ceza"],
  AZİL: ["Borçlar", "Usul"],
  EDA: ["Borçlar", "Usul"],
  HALEF: ["Medeni", "Miras", "Borçlar"],
  FUZULİ: ["Eşya", "Borçlar"],
  İSTİMLAK: ["İdare", "Eşya"],
  MÜFLİS: ["İcra", "Ticaret"],
  MAHSUP: ["Borçlar", "Vergi"],
  NİSAP: ["Anayasa", "Ticaret"],
  KAMBİYO: ["Ticaret", "İcra"],
  İMTİNA: ["Usul", "Ceza"],
  GAİP: ["Medeni", "Miras"],
  HISIM: ["Aile", "Miras"],
  TEVKİL: ["Borçlar", "Usul"],
  EMARE: ["Usul", "Ceza"],
  İRTİKAP: ["Ceza", "İdare"],
  HALEFİYET: ["Borçlar", "Ticaret"],
  SİMSARLIK: ["Ticaret", "Borçlar"],
};

/** Every category a term belongs to. */
export const categoriesOf = (q: { term: string; category: string }) =>
  termCategories[q.term] ?? [q.category];
